# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization team', '0002_auto_20160707_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='work',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='person',
            name='content',
        ),
        migrations.AddField(
            model_name='activity',
            name='content',
            field=mezzanine.core.fields.RichTextField(default='', verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='content_en',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='activity',
            name='content_fr',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='activity',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='work'),
        ),
        migrations.AddField(
            model_name='activity',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='work'),
        ),
        migrations.AddField(
            model_name='department',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='department',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=512, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_fr',
            field=models.CharField(max_length=512, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='person',
            name='bio_en',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='biography'),
        ),
        migrations.AddField(
            model_name='person',
            name='bio_fr',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='biography'),
        ),
        migrations.AddField(
            model_name='team',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='team',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_en',
            field=models.CharField(max_length=512, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_fr',
            field=models.CharField(max_length=512, null=True, verbose_name='name'),
        ),
    ]
