# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-team', '0004_auto_20160715_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='nationality',
        ),
    ]
