# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-team', '0009_auto_20160725_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sub_title_en',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='department',
            name='sub_title_fr',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='team',
            name='sub_title_en',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='team',
            name='sub_title_fr',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='sub title'),
        ),
    ]
