# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization-core', '0011_auto_20160809_1413'),
        ('organization-team', '0012_auto_20160808_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('content_fr', mezzanine.core.fields.RichTextField(null=True, verbose_name='Content')),
                ('content_en', mezzanine.core.fields.RichTextField(null=True, verbose_name='Content')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('date_begin', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('role', models.CharField(blank=True, max_length=512, verbose_name='role')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'verbose_name': 'activity',
            },
        ),
        migrations.CreateModel(
            name='TeamLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('link_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization-core.LinkType', verbose_name='link type')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization-team.Team', verbose_name='links')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='activity',
            name='person',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='person',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.AddField(
            model_name='personactivity',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization-team.Person', verbose_name='person'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization-team.Team', verbose_name='team'),
        ),
    ]
