# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-team', '0014_department_articles_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='articles_related',
            field=models.ManyToManyField(blank=True, to='organization-magazine.Article', verbose_name='Related articles'),
        ),
    ]
