# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-team', '0015_auto_20160810_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='weaving_css_class',
            field=models.CharField(blank=True, choices=[('pattern-bg--circles', 'circles'), ('pattern-bg--squares', 'squares'), ('pattern-bg--stripes', 'stripes'), ('pattern-bg--triangles', 'triangles')], max_length=64, verbose_name='background pattern'),
        ),
    ]
