# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0004_auto_20160905_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='persons',
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('internal project', 'internal project'), ('external project', 'external project')], max_length=128, verbose_name='type'),
        ),
    ]
