# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0005_auto_20160907_1046'),
        ('organization_projects', '0005_auto_20160907_1138'),
    ]

    operations = [
    ]
