# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0006_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectprogram',
            options={'verbose_name': 'program'},
        ),
        migrations.AlterModelOptions(
            name='projectprogramtype',
            options={'verbose_name': 'program type'},
        ),
    ]
