# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0009_auto_20160921_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sub_topic',
        ),
        migrations.AddField(
            model_name='projecttopic',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='organization_projects.ProjectTopic', verbose_name='parent topic'),
        ),
        migrations.DeleteModel(
            name='ProjectSubTopic',
        ),
    ]
