# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0012_projecttopicpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttopicpage',
            name='sub_title_en',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='projecttopicpage',
            name='sub_title_fr',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='sub title'),
        ),
    ]
