# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0013_auto_20160922_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttopicpage',
            options={'ordering': ('_order',), 'verbose_name': 'project topic page'},
        ),
    ]
