# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-05 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0017_auto_20160928_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_from', '-date_to'], 'verbose_name': 'project'},
        ),
    ]
