# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_media', '0006_auto_20161013_1631'),
        ('organization_projects', '0019_auto_20161007_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPlaylist',
            fields=[
                ('playlist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization_media.Playlist')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to='organization_projects.Project', verbose_name='project')),
            ],
            options={
                'abstract': False,
            },
            bases=('organization_media.playlist',),
        ),
        migrations.RemoveField(
            model_name='projectaudio',
            name='audio_ptr',
        ),
        migrations.RemoveField(
            model_name='projectaudio',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectvideo',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectvideo',
            name='video_ptr',
        ),
        migrations.DeleteModel(
            name='ProjectAudio',
        ),
        migrations.DeleteModel(
            name='ProjectVideo',
        ),
    ]
