# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-07 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0029_auto_20161107_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdemo',
            name='url',
            field=models.URLField(blank=True, max_length=512, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(help_text='http(s) or ssh', max_length=256, verbose_name='URL'),
        ),
    ]
