# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-22 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0031_auto_20161205_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='register ID'),
        ),
    ]
