# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-30 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0033_projectworkpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='external_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='external ID'),
        ),
    ]
