# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-04 17:20
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0038_projectblogpage_login_required_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectblogpage',
            name='login_required_content_en',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Login required content'),
        ),
        migrations.AddField(
            model_name='projectblogpage',
            name='login_required_content_fr',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Login required content'),
        ),
    ]
