# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-30 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0042_auto_20170118_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
    ]
