# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-03 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0046_auto_20170303_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectictdata',
            name='contact',
        ),
    ]
