# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-14 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0051_auto_20170314_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpublicdata',
            name='challenges_description',
            field=models.TextField(help_text='Full description of the challenges faced by the project (100-150 words).', verbose_name='challenges description'),
        ),
        migrations.AlterField(
            model_name='projectpublicdata',
            name='objectives_description',
            field=models.TextField(help_text='What the project is looking to gain from the collaboration and what kind of artist would be suitable (100 – 150 words).', verbose_name='objectives description'),
        ),
    ]
