# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-14 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0052_auto_20170314_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprivatedata',
            name='commitment_letter',
            field=models.FileField(help_text='Written on behalf of the whole project consortium, this letter will commit in implementing the collaboration of a residency application selected by the VERTIGO jury, on the conditions set by the project (in annex of letter: synthesis of all related information entered by project).', max_length=1024, upload_to='user/documents/%Y/%m/%d/', verbose_name='letter of commitment by the project coordinator'),
        ),
        migrations.AlterField(
            model_name='projectpublicdata',
            name='image',
            field=models.FileField(help_text='Representing the project', max_length=1024, upload_to='user/images/%Y/%m/%d/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='projectuserimage',
            name='file',
            field=models.FileField(max_length=1024, upload_to='user/images/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
