# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-12 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0043_auto_20170130_1520'),
        ('organization-projects', '0053_auto_20170314_1918'),
    ]

    operations = [
    ]
