# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-23 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0053_auto_20170314_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontact',
            name='organization_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='organization name'),
        ),
        migrations.AddField(
            model_name='projectcontact',
            name='position',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='projectpublicdata',
            name='image_credits',
            field=models.CharField(max_length=256, null=True, verbose_name='Image credits'),
        ),
    ]
