# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-23 09:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0054_auto_20170323_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpublicdata',
            name='period',
        ),
        migrations.AddField(
            model_name='projectpublicdata',
            name='implementation_duration',
            field=models.CharField(default='1', help_text='Possible duration of implementation in months (must be part of the project implementation workplan) (months)', max_length=128, verbose_name='implementation duration'),
        ),
        migrations.AddField(
            model_name='projectpublicdata',
            name='implementation_start_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 23, 9, 39, 34, 20133, tzinfo=utc), help_text='Possible start date of implementation (must be part of the project implementation workplan) (DD/MM/YYYY)', verbose_name='implementation start date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='projectcall',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='projectresidency',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='projectworkpackage',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
    ]
