# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-31 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0055_auto_20170323_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpublicdata',
            name='implementation_start_date',
            field=models.DateField(help_text='Possible start date of implementation (must be part of the project implementation workplan) (MM/DD/YYYY)', verbose_name='implementation start date'),
        ),
    ]
