# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-12 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0056_auto_20170331_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='organization_projects.ProjectTopic', verbose_name='topic'),
        ),
    ]
