# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-12 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0057_auto_20170412_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttopic',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='projecttopic',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='projecttopic',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='projecttopic',
            name='name_fr',
        ),
    ]
