# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-18 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0058_auto_20170418_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttopic',
            name='key',
            field=models.CharField(default='unknown', max_length=128, unique=True, verbose_name='key'),
            preserve_default=False,
        ),
    ]
