# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-07-13 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0019_auto_20170415_0948'),
        ('organization_projects', '0063_projectresidencyarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectResidencyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residencies', to='mezzanine_agenda.Event', verbose_name='event')),
                ('residency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='organization_projects.ProjectResidency', verbose_name='residency')),
            ],
        ),
    ]
