# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-07-13 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0064_projectresidencyevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectresidencyarticle',
            name='residency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residency_articles', to='organization_projects.ProjectResidency', verbose_name='residency'),
        ),
        migrations.AlterField(
            model_name='projectresidencyevent',
            name='residency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residency_events', to='organization_projects.ProjectResidency', verbose_name='residency'),
        ),
    ]
