# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-09-22 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0066_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectprivatedata',
            name='affiliation',
        ),
        migrations.AddField(
            model_name='project',
            name='funding',
            field=models.CharField(blank=True, choices=[('public', 'EU / National Program'), ('private', 'Privately Funded')], max_length=128, null=True, verbose_name='funding'),
        ),
        migrations.AddField(
            model_name='projectprivatedata',
            name='dimension',
            field=models.CharField(choices=[('startup', 'Start-up / Micro'), ('sme', 'SME'), ('large', 'Large')], max_length=128, null=True, verbose_name='dimension'),
        ),
        migrations.AddField(
            model_name='projectprivatedata',
            name='funding_programme',
            field=models.CharField(help_text='Designation of EU/National Funding Programme', max_length=512, null=True, verbose_name='funding programme'),
        ),
        migrations.AddField(
            model_name='projectprivatedata',
            name='investor_letter',
            field=models.FileField(help_text='If the organisation is a Start-Up or micro enterprise (less than 3 years and/or less than 10 staff members), the presentation of letter of recommendation from an investor is mandatory to apply to this call.', max_length=1024, null=True, upload_to='user/documents/%Y/%m/%d/', verbose_name='letter of recommendations from investor (e.g VC)'),
        ),
        migrations.AddField(
            model_name='projectpublicdata',
            name='implementation_period',
            field=models.DateField(help_text='Possible period for direct cooperation with the artist (must be within the period of the project implementation workplan) (MM/DD/YYYY)', null=True, verbose_name='period for direct cooperation'),
        ),
        migrations.AlterField(
            model_name='projectpublicdata',
            name='brief_description',
            field=models.CharField(help_text='Brief description of the technology/challenges faced by the project (110 characters max).', max_length=110, verbose_name='brief description'),
        ),
        migrations.AlterField(
            model_name='projectpublicdata',
            name='challenges_description',
            field=models.TextField(help_text='Description of the project technology to be made available to artist + challenges it produces (100 words - must include the elements to be made available to the artist with sufficient functional and implementation details for enabling him/her to elaborate a technical approach)).', verbose_name='challenges description'),
        ),
        migrations.AlterField(
            model_name='projectpublicdata',
            name='implementation_start_date',
            field=models.DateField(help_text='Possible period for the implementation of the residency (must be within the period of the project implementation workplan) (MM/DD/YYYY)', verbose_name='residency start date'),
        ),
    ]
