# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-03 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0068_auto_20170929_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpublicdata',
            name='implementation_duration',
            field=models.CharField(help_text='Possible duration of implementation in months (must be part of the project implementation workplan) (months)', max_length=128, verbose_name='residency duration'),
        ),
    ]
