# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-26 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0044_project_is_archive'),
        ('organization_projects', '0055_auto_20170427_1211'),
        ('organization_projects', '0069_auto_20171003_1634'),
    ]

    operations = [
    ]
