# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-12-29 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0070_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectResidencyPrivateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_cv', models.FileField(max_length=10240, null=True, upload_to='user/documents/%Y/%m/%d/', verbose_name='Artist CV')),
                ('motivation_letter', models.FileField(help_text='Including expectations for the co-creation process', max_length=1024, null=True, upload_to='user/documents/%Y/%m/%d/', verbose_name='Letter of Motivation for ART-ICT co-creation')),
                ('comments', models.TextField(blank=True, help_text='In order to avoid conflict interests', null=True, verbose_name='Proposals of experts to be included and request of experts to be excluded from the evaluation process')),
                ('other', models.TextField(blank=True, null=True, verbose_name='Other')),
                ('residency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_data', to='organization-projects.ProjectResidency', verbose_name='residency private data')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectResidencyPublicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords_string', models.CharField(blank=True, editable=False, max_length=500)),
                ('descriptive_title', models.CharField(blank=True, help_text='To be used for wider communication strategy (eg. summaries and Twitter)', max_length=110, null=True, verbose_name='Descriptive title of proposal (110 characters max)')),
                ('brief_description', models.TextField(blank=True, null=True, verbose_name='Brief description of proposal (150 - 200 words)')),
                ('residency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_data', to='organization-projects.ProjectResidency', verbose_name='residency public data')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projectblock',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='projectblock',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='projectblock',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projectblogpage',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='projectblogpage',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='projectblogpage',
            name='login_required_content_fr',
        ),
        migrations.RemoveField(
            model_name='projectblogpage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projectcall',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='projectcall',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='projectcall',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projectcallblock',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='projectcallblock',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='projectcallblock',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projectcalllink',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projectdemo',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='projectdemo',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projectlink',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projectprogram',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='projectprogram',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='projectprogramtype',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='projectprogramtype',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='projectrelatedtitle',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projecttopic',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='projecttopic',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='projecttopicpage',
            name='sub_title_fr',
        ),
        migrations.AlterField(
            model_name='project',
            name='validation_status',
            field=models.IntegerField(choices=[(0, 'rejected'), (1, 'pending'), (2, 'in process'), (3, 'accepted'), (4, 'copied')], default=1, verbose_name='validation status'),
        ),
        migrations.AlterField(
            model_name='projectpublicdata',
            name='implementation_start_date',
            field=models.DateField(help_text='Possible period for the implementation of the residency (must be within the period of the project implementation workplan) (MM/DD/YYYY)', null=True, verbose_name='residency start date'),
        ),
    ]
