# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-11-07 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0070_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='projectblogpage',
            name='slug',
            field=models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='projectcall',
            name='slug',
            field=models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='projectdemo',
            name='slug',
            field=models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='projectresidency',
            name='slug',
            field=models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, verbose_name='URL'),
        ),
    ]
