# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-12-29 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0071_auto_20171229_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprivatedata',
            name='commitment_letter',
            field=models.FileField(blank=True, help_text='Written on behalf of the whole project consortium, this letter will commit in implementing the collaboration of a residency application selected by the VERTIGO jury, on the conditions set by the project (in annex of letter: synthesis of all related information entered by project).<br>Please <a href="http://vertigo.starts.eu/media/uploads/vertigo%20starts/CALL/vertigo_loc_v3.rtf">download and use the template letter.</a>', max_length=1024, null=True, upload_to='user/documents/%Y/%m/%d/', verbose_name='letter of commitment by the project coordinator'),
        ),
        migrations.AlterField(
            model_name='projectprivatedata',
            name='dimension',
            field=models.CharField(blank=True, choices=[('startup', 'Start-up / Micro'), ('sme', 'SME'), ('large', 'Large')], max_length=128, null=True, verbose_name='dimension'),
        ),
        migrations.AlterField(
            model_name='projectprivatedata',
            name='funding_programme',
            field=models.CharField(blank=True, help_text='Designation of EU/National Funding Programme', max_length=512, null=True, verbose_name='funding programme'),
        ),
        migrations.AlterField(
            model_name='projectprivatedata',
            name='investor_letter',
            field=models.FileField(blank=True, help_text='If the organisation is a Start-Up or micro enterprise (less than 3 years and/or less than 10 staff members), the presentation of letter of recommendation from an investor is mandatory to apply to this call.', max_length=1024, null=True, upload_to='user/documents/%Y/%m/%d/', verbose_name='letter of recommendations from investor (e.g VC)'),
        ),
    ]
