# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-02-13 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0071_projectcollection_projectcollectionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcollection',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='projectcollection',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='projectcollection',
            name='name_en',
            field=models.CharField(max_length=512, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='projectcollection',
            name='name_fr',
            field=models.CharField(max_length=512, null=True, verbose_name='name'),
        ),
    ]
