# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-04-07 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0071_auto_20180313_2231'),
        ('organization-projects', '0071_auto_20171222_1121'),
    ]

    operations = [
    ]
