# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-03-06 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0072_auto_20180223_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamiccontentproject',
            options={'ordering': ('_order',), 'verbose_name': 'Linked Project'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='topics',
        ),
    ]
