# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-06-15 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0073_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='access',
            field=models.CharField(choices=[('public', 'public'), ('shared', 'shared'), ('private', 'private')], default='private', max_length=64, verbose_name='access rights'),
        ),
    ]
