# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-18 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0073_project_concepts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='access',
            field=models.CharField(choices=[('public', 'public'), ('shared', 'shared'), ('private', 'private')], default='private', max_length=64, verbose_name='access rights'),
        ),
    ]
