# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-04-30 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0074_auto_20180403_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='repositorysystem',
            name='branch_command',
        ),
        migrations.RemoveField(
            model_name='repositorysystem',
            name='checkout_command',
        ),
        migrations.RemoveField(
            model_name='repositorysystem',
            name='clone_command',
        ),
        migrations.RemoveField(
            model_name='repositorysystem',
            name='pull_command',
        ),
        migrations.AddField(
            model_name='repository',
            name='vendor',
            field=models.CharField(choices=[('gitlab', 'Gitlab')], default='gitlab', max_length=64, verbose_name='vendor'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(help_text='http(s)', max_length=256, verbose_name='URL'),
        ),
    ]
