# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-24 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0074_auto_20180615_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='projectcall',
            options={'ordering': ['-date_from', 'title'], 'verbose_name': 'project call', 'verbose_name_plural': 'project calls'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projectblock',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='projectblock',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='projectblock',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projectblogpage',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='projectblogpage',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='projectblogpage',
            name='login_required_content_fr',
        ),
        migrations.RemoveField(
            model_name='projectblogpage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projectcall',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='projectcall',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='projectcall',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projectcallblock',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='projectcallblock',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='projectcallblock',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projectcalllink',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projectdemo',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='projectdemo',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projectlink',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projectprogram',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='projectprogram',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='projectprogramtype',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='projectprogramtype',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='projectrelatedtitle',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projecttopic',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='projecttopic',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='projecttopicpage',
            name='sub_title_fr',
        ),
        migrations.AlterField(
            model_name='project',
            name='validation_status',
            field=models.IntegerField(choices=[(0, 'rejected'), (1, 'draft'), (2, 'submitted'), (3, 'validated'), (4, 'implemented'), (5, 'closed'), (6, 'copied')], default=1, verbose_name='validation status'),
        ),
        migrations.AlterField(
            model_name='projectprivatedata',
            name='description',
            field=models.TextField(blank=True, help_text='(500 - 1000 words)', verbose_name='project description'),
        ),
    ]
