# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-08 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0075_auto_20180924_1057'),
        ('organization-projects', '0073_project_concepts'),
    ]

    operations = [
    ]
