# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-04-30 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0075_auto_20180430_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='description',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='name',
        ),
    ]
