# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-04-30 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0076_auto_20180430_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_repositories', to='organization_projects.Project', verbose_name='project')),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_repositories', to='organization_projects.Repository', verbose_name='repository')),
            ],
            options={
                'verbose_name': 'project repository',
                'verbose_name_plural': 'project repositories',
            },
        ),
    ]
