# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-05-03 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organization_projects', '0077_projectrepository'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pivot_Project_ProjectCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('object_id', models.PositiveIntegerField(editable=False, null=True, verbose_name='related object')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_collection_collection', to='organization_projects.ProjectCollection', verbose_name='collection')),
                ('content_type', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_pivot', to='organization_projects.Project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'Dynamic Collection Project',
                'ordering': ('_order',),
            },
        ),
        migrations.RemoveField(
            model_name='dynamiccollectionproject',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='dynamiccollectionproject',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='dynamiccollectionproject',
            name='project',
        ),
        migrations.DeleteModel(
            name='DynamicCollectionProject',
        ),
    ]
