# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-05 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0077_auto_20181105_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='content_en',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='call',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='call',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
    ]
