# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-16 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0078_auto_20181106_0035'),
        ('organization-projects', '0075_auto_20181102_1151'),
    ]

    operations = [
    ]
