# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-04 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0076_auto_20181204_1104'),
        ('organization-projects', '0079_merge_20181116_1731'),
    ]

    operations = [
    ]
