# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-12 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization-projects', '0079_merge_20181116_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcallimage',
            name='credits_fr',
        ),
        migrations.RemoveField(
            model_name='projectcallimage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='credits_fr',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projectresidencyimage',
            name='credits_fr',
        ),
        migrations.RemoveField(
            model_name='projectresidencyimage',
            name='title_fr',
        ),
        migrations.AddField(
            model_name='call',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_managers', to=settings.AUTH_USER_MODEL, verbose_name='call manager'),
        ),
    ]
