# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-23 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0078_auto_20190117_1158'),
        ('organization-projects', '0079_auto_20190110_1054'),
    ]

    operations = [
    ]
