# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-06-01 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0079_auto_20180514_1637'),
        ('organization_projects', '0073_project_concepts'),
    ]

    operations = [
    ]
