# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-17 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0080_merge_20181204_1106'),
        ('organization-projects', '0080_auto_20181212_1211'),
    ]

    operations = [
    ]
