# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-06-01 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0080_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pivot_project_projectcollection',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_pivot', to='organization_projects.ProjectCollection', verbose_name='collection'),
        ),
    ]
