# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-21 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0081_auto_20190130_1553'),
        ('organization_projects', '0075_auto_20180816_1610'),
    ]

    operations = [
    ]
