# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-06-07 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0081_auto_20180601_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title'], 'permissions': (('view_project', 'Can view project'), ('edit_project', 'Can edit project')), 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
    ]
