# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-16 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0082_auto_20190515_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresidency',
            name='address_2',
            field=models.TextField(blank=True, verbose_name='address 2'),
        ),
        migrations.AddField(
            model_name='projectresidencyuserimage',
            name='type',
            field=models.CharField(choices=[('logo', 'logo'), ('logo_white', 'logo white'), ('logo_black', 'logo black'), ('logo_header', 'logo header'), ('logo_footer', 'logo footer'), ('slider', 'slider'), ('card', 'card'), ('page_slider', 'page - slider'), ('page_featured', 'page - featured'), ('header__responsive-logo-footer', 'responsive logo footer'), ('header__responsive-frame-video', 'responsive frame video')], max_length=64, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='projectuserimage',
            name='type',
            field=models.CharField(choices=[('logo', 'logo'), ('logo_white', 'logo white'), ('logo_black', 'logo black'), ('logo_header', 'logo header'), ('logo_footer', 'logo footer'), ('slider', 'slider'), ('card', 'card'), ('page_slider', 'page - slider'), ('page_featured', 'page - featured'), ('header__responsive-logo-footer', 'responsive logo footer'), ('header__responsive-frame-video', 'responsive frame video')], max_length=64, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='projectresidency',
            name='address',
            field=models.TextField(blank=True, verbose_name='address 1'),
        ),
    ]
