# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-06-07 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0082_auto_20180607_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title'], 'permissions': (('view_project', 'Can view project'),), 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
    ]
