# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-04 21:21
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0083_auto_20190221_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='content_en',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='content_fr',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
    ]
