# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-07-09 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organization_magazine', '0022_merge'),
        ('organization_projects', '0084_project_is_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pivot_ProjectTopic_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('object_id', models.PositiveIntegerField(editable=False, null=True, verbose_name='related object')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics_pivot', to='organization_magazine.Article', verbose_name='article')),
                ('content_type', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type')),
                ('project_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles_pivot', to='organization_projects.ProjectTopic', verbose_name='project topic')),
            ],
            options={
                'verbose_name': 'Project Topic <--> Article',
                'ordering': ('_order',),
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('internal', 'internal'), ('external', 'external'), ('tutorial', 'tutorial'), ('project', 'project')], max_length=128, verbose_name='type'),
        ),
    ]
