# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-24 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0083_auto_20190516_1812'),
        ('organization-projects', '0084_auto_20190304_2221'),
    ]

    operations = [
    ]
