# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-27 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0085_merge_20190524_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projectpageblock',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='projectpageblock',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='projectpageblock',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='projectpageimage',
            name='credits_fr',
        ),
        migrations.RemoveField(
            model_name='projectpageimage',
            name='title_fr',
        ),
        migrations.AlterField(
            model_name='projectpageimage',
            name='type',
            field=models.CharField(choices=[('logo', 'logo'), ('logo_white', 'logo white'), ('logo_black', 'logo black'), ('logo_header', 'logo header'), ('logo_footer', 'logo footer'), ('slider', 'slider'), ('card', 'card'), ('page_slider', 'page - slider'), ('page_featured', 'page - featured'), ('header__responsive-logo-footer', 'responsive logo footer'), ('header__responsive-frame-video', 'responsive frame video')], max_length=64, verbose_name='type'),
        ),
    ]
