# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-07-30 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0086_auto_20180723_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('version', models.CharField(help_text='Best practice is to follow semver (semantic versionning)', max_length=256, verbose_name='Release version')),
                ('name', models.CharField(help_text='The release codename (if any)', max_length=256, null=True, verbose_name='Release name')),
                ('repository_ref', models.CharField(help_text='Can be a tag, a commit sha or a branch', max_length=256, null=True, verbose_name='Repository ref')),
                ('requirements', models.TextField(help_text='Only common requirements for all platforms (e.g. Python >= 2.7)', verbose_name='requirements')),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='organization-projects.Repository', verbose_name='repository')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RepositoryReleaseBinary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('os', models.CharField(blank=True, choices=[('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux'), ('android', 'Android'), ('ios', 'iOS'), ('multi', 'Multi-platforms'), ('none', 'Not applicable')], max_length=128, null=True, verbose_name='os')),
                ('url', models.CharField(help_text='http(s)', max_length=1024, verbose_name='URL')),
                ('requirements', models.TextField(help_text='Only specific requirements for this binary (e.g. macOS <= 10.12)', verbose_name='requirements')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
