# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-09-13 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0086_auto_20180723_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='vendor',
            field=models.CharField(choices=[('gitlab', 'Gitlab'), ('github', 'Github')], default='gitlab', max_length=64, verbose_name='vendor'),
        ),
    ]
