# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-07-30 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0087_repositoryrelease_repositoryreleasebinary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repositoryreleasebinary',
            options={'verbose_name_plural': 'Repository release binaries'},
        ),
        migrations.AddField(
            model_name='repositoryreleasebinary',
            name='repository_release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='binaries', to='organization-projects.RepositoryRelease', verbose_name='repository release'),
        ),
        migrations.AlterField(
            model_name='repositoryrelease',
            name='name',
            field=models.CharField(blank=True, help_text='The release codename (if any)', max_length=256, null=True, verbose_name='Release name'),
        ),
        migrations.AlterField(
            model_name='repositoryrelease',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='organization-projects.Repository', verbose_name='repository'),
        ),
        migrations.AlterField(
            model_name='repositoryrelease',
            name='requirements',
            field=models.TextField(blank=True, help_text='Only common requirements for all platforms (e.g. Python >= 2.7)', null=True, verbose_name='requirements'),
        ),
        migrations.AlterField(
            model_name='repositoryrelease',
            name='version',
            field=models.CharField(help_text='Without the "v" prefix. Best practice is to follow semver (semantic versionning).', max_length=256, verbose_name='Release version'),
        ),
        migrations.AlterField(
            model_name='repositoryreleasebinary',
            name='os',
            field=models.CharField(blank=True, choices=[('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux'), ('android', 'Android'), ('ios', 'iOS'), ('cross', 'Cross-platforms'), ('none', 'Not applicable')], max_length=128, null=True, verbose_name='os'),
        ),
    ]
