# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-06 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0087_auto_20191006_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectresidencyarticle',
            old_name='file',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='projectresidencyarticle',
            old_name='credits',
            new_name='image_credits',
        ),
    ]
