# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-11 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0088_auto_20191006_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectresidencyarticle',
            name='image_credits',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='credits'),
        ),
    ]
