# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-18 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0074_auto_20180918_1524'),
        ('organization-projects', '0089_merge_20181018_1145'),
    ]

    operations = [
    ]
