# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-26 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0090_auto_20190703_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, choices=[('internal', 'internal'), ('external', 'external'), ('industrial', 'industrial')], max_length=128, verbose_name='type'),
        ),
    ]
