# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-19 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0088_auto_20181002_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(help_text='http(s) or ssh', max_length=256, verbose_name='URL'),
        ),
    ]
