# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-02-26 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0091_auto_20200214_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectresidencyarticle',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residencies', to='organization-magazine.ArticleMultiSite', verbose_name='article'),
        ),
    ]
