# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-28 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0091_auto_20181019_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_fr',
        ),
    ]
