# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0091_auto_20200626_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, choices=[('internal', 'Internal project'), ('external', 'National or European project'), ('industrial', 'Industrial project')], max_length=128, verbose_name='type'),
        ),
    ]
