# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-12 16:13
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0092_auto_20200226_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresidency',
            name='outcome',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='outcome'),
        ),
    ]
