# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-28 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0092_auto_20200703_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='organization-projects.Project', verbose_name='project'),
            preserve_default=False,
        ),
    ]
