# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-12 11:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0093_project_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('internal', 'internal'), ('external', 'external'), ('tutorial', 'tutorial'), ('project', 'project')], default='project', max_length=128, verbose_name='type'),
        ),
    ]
