# Generated by Django 3.2.8 on 2021-11-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0094_auto_20210823_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='display_navbar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projecttopicpage',
            name='display_navbar',
            field=models.BooleanField(default=True),
        ),
    ]
