# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-12 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0094_auto_20190212_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttopic',
            options={'ordering': ['key'], 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterField(
            model_name='projecttopic',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='organization_projects.ProjectTopic', verbose_name='parent tag'),
        ),
    ]
