# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-27 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("organization-projects", "0095_auto_20190212_1619")]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="access",
            field=models.CharField(
                choices=[
                    ("public", "public"),
                    ("shared", "shared"),
                    ("private", "private"),
                ],
                default="public",
                max_length=64,
                verbose_name="access rights",
            ),
        )
    ]
