# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-06 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0096_auto_20200427_1533'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='project',
        #     name='concepts',
        # ),
    ]
