# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-15 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0097_remove_project_concepts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='concepts',
        ),
    ]
