# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-12 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0098_remove_project_concepts'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active_strategy',
            field=models.CharField(choices=[('repository_release', 'repository release'), ('external_release', 'external release')], default='repository_release', max_length=128, verbose_name='active strategy'),
        ),
        migrations.AddField(
            model_name='project',
            name='custom_link_url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='custom link url'),
        ),
        migrations.AddField(
            model_name='project',
            name='git_ref_archive',
            field=models.CharField(default='master', max_length=128, verbose_name='git ref archive'),
        ),
        migrations.AddField(
            model_name='project',
            name='git_tag',
            field=models.CharField(blank=True, default='None', max_length=128, null=True, verbose_name='git tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='include_binaries',
            field=models.BooleanField(default=True, verbose_name='include binaries'),
        ),
        migrations.AddField(
            model_name='project',
            name='include_sources',
            field=models.BooleanField(default=True, verbose_name='include sources'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='If this is a premium project.', verbose_name='is premium'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='If this is a premium project protected by an authorization key.', verbose_name='is protected'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_release_ref',
            field=models.CharField(blank=True, default='latest', max_length=128, null=True, verbose_name='project release ref'),
        ),
        migrations.AddField(
            model_name='project',
            name='protection_endpoint',
            field=models.CharField(blank=True, default='None', max_length=128, null=True, verbose_name='protection endpoint'),
        ),
        migrations.AddField(
            model_name='project',
            name='protection_unlock_url',
            field=models.CharField(blank=True, default='None', max_length=128, null=True, verbose_name='protection unlock url'),
        ),
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.CharField(default='1.2', max_length=128, verbose_name='version'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('internal', 'internal'), ('external', 'external')], default='internal', max_length=128, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='projectblogpage',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Published'), (3, 'Archived')], default=2, help_text='With Draft chosen, will only be shown for admin users on the site.', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectcall',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Published'), (3, 'Archived')], default=2, help_text='With Draft chosen, will only be shown for admin users on the site.', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectcollection',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Published'), (3, 'Archived')], default=2, help_text='With Draft chosen, will only be shown for admin users on the site.', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectdemo',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Published'), (3, 'Archived')], default=2, help_text='With Draft chosen, will only be shown for admin users on the site.', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectresidency',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Published'), (3, 'Archived')], default=2, help_text='With Draft chosen, will only be shown for admin users on the site.', verbose_name='Status'),
        ),
    ]
