# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-27 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0100_auto_20220715_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('internal', 'internal'), ('external', 'external'), ('project', 'project')], default='project', max_length=128, verbose_name='type'),
        ),
    ]
