# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-01 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0101_auto_20220727_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_url',
            field=models.CharField(default='', max_length=512, verbose_name='external url'),
        ),
    ]
