# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-02 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0102_project_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='external_url',
            field=models.CharField(blank=True, default='None', max_length=512, null=True, verbose_name='external url'),
        ),
    ]
