# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-09-21 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0103_auto_20220802_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='external_url',
            field=models.URLField(blank=True, default='None', max_length=1024, null=True, verbose_name='external url'),
        ),
    ]
