# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-03 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0105_auto_20220929_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_git_repository',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='external git repository'),
        ),
    ]
