# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-26 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0106_project_external_git_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='custom_link_url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='custom link url'),
        ),
        migrations.AlterField(
            model_name='project',
            name='external_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='external url'),
        ),
        migrations.AlterField(
            model_name='project',
            name='git_tag',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='git tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='protection_endpoint',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='protection endpoint'),
        ),
        migrations.AlterField(
            model_name='project',
            name='protection_unlock_url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='protection unlock url'),
        ),
        migrations.AlterField(
            model_name='project',
            name='version',
            field=models.CharField(max_length=128, verbose_name='version'),
        ),
    ]
