# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-26 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0107_auto_20221026_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='version',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='version'),
        ),
    ]
