# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-14 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0108_auto_20221026_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='custom_link_url',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='custom link url'),
        ),
        migrations.AlterField(
            model_name='project',
            name='protection_endpoint',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='protection endpoint'),
        ),
        migrations.AlterField(
            model_name='project',
            name='protection_unlock_url',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='protection unlock url'),
        ),
    ]
