# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-14 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0109_auto_20230212_0124'),
        ('organization_projects', '0109_auto_20230214_1231'),
    ]

    operations = [
    ]
