# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-16 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0110_merge_20230214_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/projects/images/'),
        ),
    ]
