# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-19 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0111_auto_20230216_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_download_repo',
            field=models.BooleanField(default=False, help_text='Show download repository button.', verbose_name='show download repository'),
        ),
        migrations.AlterField(
            model_name='project',
            name='active_strategy',
            field=models.CharField(choices=[('git_ref_archive', 'git_ref_archive'), ('repo_release', 'repo_release'), ('custom_links', 'custom_links'), ('project_release', 'project_release')], default='project_release', max_length=128, verbose_name='active strategy'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('internal', 'internal'), ('external', 'external'), ('tutorial', 'tutorial'), ('project', 'project')], default='project', max_length=128, verbose_name='type'),
        ),
    ]
