# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-12 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0112_auto_20230219_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='submitted_on',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
