# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-17 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_core', '0006_auto_20230417_1633'),
        ('organization-projects', '0113_auto_20230412_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='meta_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='organization_core.MetaCategory', verbose_name='meta categories'),
        ),
    ]
