# Generated by Django 3.2.18 on 2023-04-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0096_auto_20211202_1444'),
        ('organization_projects', '0115_auto_20230418_1054'),
    ]

    operations = [
    ]
