# Generated by Django 3.2.18 on 2023-04-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0116_auto_20230424_1520'),
        ('organization_projects', '0117_auto_20230424_1857'),
    ]

    operations = [
    ]
