# Generated by Django 3.2.18 on 2023-04-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0119_auto_20230425_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttopic',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttopic',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
