# Generated by Django 3.2.19 on 2023-05-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0120_auto_20230426_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Language',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='project_languages', to='organization_projects.ProjectLanguage', verbose_name='languages'),
        ),
    ]
