# Generated by Django 3.2.19 on 2023-05-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0122_auto_20230523_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttopic',
            old_name='featured',
            new_name='extenal_featured',
        ),
        migrations.RemoveField(
            model_name='projecttopic',
            name='validated',
        ),
        migrations.AddField(
            model_name='projecttopic',
            name='internal_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttopic',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Published')], default=2, verbose_name='Status'),
        ),
    ]
