# Generated by Django 3.2.19 on 2023-05-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0123_auto_20230523_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttopic',
            old_name='extenal_featured',
            new_name='external_featured',
        ),
    ]
