# Generated by Django 3.2.19 on 2023-05-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0124_rename_extenal_featured_projecttopic_external_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttopic',
            options={'ordering': ['key'], 'verbose_name': 'topic'},
        ),
    ]
