# Generated by Django 3.2.19 on 2023-05-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0126_alter_projecttopic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttopic',
            name='status',
            field=models.IntegerField(choices=[(0, 'rejected'), (1, 'pending'), (2, 'accepted'), (3, 'to be merged')], default=1, verbose_name='Status'),
        ),
    ]
