# Generated by Django 3.2.19 on 2023-06-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0127_alter_projecttopic_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttopic',
            name='external_featured',
        ),
        migrations.RemoveField(
            model_name='projecttopic',
            name='internal_featured',
        ),
        migrations.AddField(
            model_name='projecttopic',
            name='is_faceted',
            field=models.BooleanField(default=False, help_text='wether this topic is displayed as a filter in the search facets list'),
        ),
        migrations.AddField(
            model_name='projecttopic',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='wether this topic is featured for external applications'),
        ),
    ]
