# Generated by Django 3.2.19 on 2023-06-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0131_alter_project_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='access',
            field=models.CharField(choices=[('public', 'public'), ('shared', 'shared'), ('private', 'private')], default='public', max_length=64, verbose_name='access rights'),
        ),
    ]
