# Generated by Django 3.2.19 on 2023-06-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0131_auto_20230602_1515'),
        ('organization_projects', '0132_alter_repository_access'),
    ]

    operations = [
    ]
