# Generated by Django 3.2.19 on 2023-06-09 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization_projects', '0134_auto_20230609_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttopic',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projecttopics', to='auth.user', verbose_name='Author'),
            preserve_default=False,
        ),
    ]
