# Generated by Django 3.2.19 on 2023-07-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0135_projecttopic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_commits',
            field=models.BooleanField(default=True, help_text='Show project repository commits.', verbose_name='show repository commits'),
        ),
    ]
