# Generated by Django 3.2.19 on 2023-08-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0137_projecttopic_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['is_featured', 'updated', 'title'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='wether this topic is featured for external applications'),
        ),
    ]
