# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayableimage',
            name='type',
            field=models.CharField(choices=[('logo', 'logo'), ('slider', 'slider'), ('card', 'card'), ('content', 'content')], max_length=64, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='modelimage',
            name='type',
            field=models.CharField(choices=[('logo', 'logo'), ('slider', 'slider'), ('card', 'card'), ('content', 'content')], max_length=64, verbose_name='type'),
        ),
    ]
