# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20160725_0143'),
        ('organization-core', '0003_category_pageblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblock',
            name='content_en',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='content_fr',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.Page', verbose_name='page'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='title_en',
            field=models.CharField(max_length=1024, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='title_fr',
            field=models.CharField(max_length=1024, null=True, verbose_name='name'),
        ),
    ]
