# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0003_auto_20160901_1555'),
        ('organization-core', '0004_auto_20160901_1555'),
        ('organization-projects', '0002_auto_20160901_1555'),
        ('organization-media', '0006_auto_20160901_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomDisplayable',
        ),
        migrations.DeleteModel(
            name='CustomModel',
        ),
        migrations.DeleteModel(
            name='DisplayableBlock',
        ),
        migrations.DeleteModel(
            name='DisplayableImage',
        ),
        migrations.DeleteModel(
            name='DisplayableLink',
        ),
        migrations.DeleteModel(
            name='ModelBlock',
        ),
        migrations.DeleteModel(
            name='ModelImage',
        ),
        migrations.DeleteModel(
            name='ModelLink',
        ),
    ]
