# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization-core', '0007_auto_20160726_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpage',
            name='photo',
            field=mezzanine.core.fields.FileField(blank=True, max_length=1024, verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='photo_alignment',
            field=models.CharField(blank=True, choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], default='left', max_length=32, verbose_name='photo alignment'),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='photo_card',
            field=mezzanine.core.fields.FileField(blank=True, max_length=1024, verbose_name='card photo'),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='photo_card_credits',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='photo card credits'),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='photo_credits',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='photo credits'),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='photo_description',
            field=models.TextField(blank=True, verbose_name='photo description'),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='photo_slider',
            field=mezzanine.core.fields.FileField(blank=True, max_length=1024, verbose_name='slider photo'),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='photo_slider_credits',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='photo slider credits'),
        ),
    ]
