# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 14:56
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization-core', '0011_auto_20160809_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageblock',
            options={'ordering': ('_order',), 'verbose_name': 'page block'},
        ),
        migrations.AddField(
            model_name='pageblock',
            name='_order',
            field=mezzanine.core.fields.OrderField(null=True, verbose_name='Order'),
        ),
    ]
