# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-pages', '0004_auto_20160907_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobresponse',
            name='job_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_response', to='organization-pages.JobOffer', verbose_name='job offer'),
        ),
    ]
