# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('organization-pages', '0005_auto_20160907_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobresponse',
            name='site',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobresponse',
            name='slug',
            field=models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='jobresponse',
            name='title',
            field=models.CharField(default='job', max_length=500, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
