# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-pages', '0006_auto_20160908_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobresponse',
            name='cover_letter',
            field=models.FileField(max_length=1024, upload_to='job_responses/%Y/%m/%d/', verbose_name='cover letter'),
        ),
        migrations.AlterField(
            model_name='jobresponse',
            name='curriculum_vitae',
            field=models.FileField(max_length=1024, upload_to='job_responses/%Y/%m/%d/', verbose_name='curriculum vitae'),
        ),
    ]
