# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20151223_1313'),
        ('organization magazine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('blogpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BlogPost')),
                ('sub_title', models.CharField(blank=True, max_length=1000, verbose_name='sub title')),
                ('sub_title_fr', models.CharField(blank=True, max_length=1000, null=True, verbose_name='sub title')),
                ('sub_title_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='sub title')),
            ],
            options={
                'verbose_name': 'article',
            },
            bases=('blog.blogpost',),
        ),
    ]
