# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0002_auto_20160824_0020'),
        ('organization-magazine', '0002_auto_20160824_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization-network.Department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='type',
            field=models.CharField(choices=[('logo', 'logo'), ('slider', 'slider'), ('card', 'card'), ('page_slider', 'page slider')], max_length=64, verbose_name='type'),
        ),
    ]
