# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_magazine', '0004_dynamiccontentarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamiccontentarticle',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_content_articles', to='organization_magazine.Article', verbose_name='article'),
        ),
    ]
