# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-24 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_magazine', '0005_auto_20160923_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='brief',
            name='title_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
    ]
