# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0005_auto_20160825_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='topics', to='organization-magazine.Article', verbose_name='articles'),
        ),
    ]
