# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0006_auto_20160728_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='articles',
            field=models.ManyToManyField(blank=True, to='organization-magazine.Article', verbose_name='articles'),
        ),
    ]
