# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0007_auto_20160825_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brief',
            name='external_content_en',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='external_content_fr',
        ),
    ]
