# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0008_topic_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='sort_order',
            field=models.IntegerField(blank=True, db_index=True, default=1),
            preserve_default=False,
        ),
    ]
