# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0009_brief_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brief',
            options={'ordering': ['sort_order'], 'verbose_name': 'brief'},
        ),
    ]
