# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-12 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0010_articleaudio_articlevideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleaudio',
            options={'verbose_name': 'audio'},
        ),
    ]
