# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_media', '0005_auto_20160930_1849'),
        ('organization_magazine', '0010_articleaudio_articlevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePlaylist',
            fields=[
                ('playlist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization_media.Playlist')),
            ],
            options={
                'abstract': False,
            },
            bases=('organization_media.playlist',),
        ),
        migrations.RemoveField(
            model_name='articleaudio',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articleaudio',
            name='audio_ptr',
        ),
        migrations.RemoveField(
            model_name='articlevideo',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlevideo',
            name='video_ptr',
        ),
    ]
