# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_magazine', '0011_auto_20161013_1631'),
        ('organization_media', '0006_auto_20161013_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleAudio',
        ),
        migrations.DeleteModel(
            name='ArticleVideo',
        ),
        migrations.AddField(
            model_name='articleplaylist',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to='organization_magazine.Article', verbose_name='article'),
        ),
    ]
