# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_media', '0009_auto_20161013_2353'),
        ('organization_magazine', '0012_auto_20161013_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleplaylist',
            name='playlist_ptr',
        ),
        migrations.AddField(
            model_name='articleplaylist',
            name='playlistrelated_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization_media.PlaylistRelated'),
            preserve_default=False,
        ),
    ]
