# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0013_auto_20160812_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brief',
            options={'verbose_name': 'brief'},
        ),
        migrations.RemoveField(
            model_name='brief',
            name='sort_order',
        ),
    ]
