# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_magazine', '0013_auto_20161013_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='style',
            field=models.CharField(choices=[('grey', 'grey'), ('yellow', 'yellow'), ('black', 'black')], default='', max_length=16, verbose_name='style'),
            preserve_default=False,
        ),
    ]
