# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0015_auto_20160818_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brief',
            name='local_content',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='local_content_en',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='local_content_fr',
        ),
    ]
