# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-04 09:26
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization_magazine', '0016_auto_20161028_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content_en',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_fr',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
    ]
