# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0016_auto_20160818_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='external_content',
            field=models.URLField(default=1, max_length=1000, verbose_name='external content'),
            preserve_default=False,
        ),
    ]
