# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0017_brief_external_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='external_content_en',
            field=models.URLField(max_length=1000, null=True, verbose_name='external content'),
        ),
        migrations.AddField(
            model_name='brief',
            name='external_content_fr',
            field=models.URLField(max_length=1000, null=True, verbose_name='external content'),
        ),
    ]
