# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0018_auto_20160818_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='external_content',
            field=models.URLField(max_length=1000, null=True, verbose_name='external content'),
        ),
    ]
