# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-12-29 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0020_auto_20171221_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sub_title_fr',
        ),
        migrations.RemoveField(
            model_name='articleimage',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='articlerelatedtitle',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='text_button_fr',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='content_fr',
        ),
    ]
