# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-17 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-core', '0006_auto_20230417_1633'),
        ('organization-magazine', '0023_auto_20181002_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='organization-core.MetaCategory', verbose_name='meta categories'),
        ),
    ]
