# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-16 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0023_auto_20181105_2349'),
        ('organization-magazine', '0022_auto_20181102_1151'),
    ]

    operations = [
    ]
