# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-24 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0026_auto_20190515_2245'),
        ('organization-magazine', '0027_auto_20190402_1502'),
    ]

    operations = [
    ]
