# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-09 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0030_auto_20191006_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMultiSite',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('organization-magazine.article',),
        ),
    ]
