# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-08 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0034_auto_20190703_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sub_title_en',
        ),
        migrations.RemoveField(
            model_name='articleimage',
            name='credits_en',
        ),
        migrations.RemoveField(
            model_name='articleimage',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='articleimage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='articlerelatedtitle',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='text_button_en',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='content_en',
        ),
    ]
