# Generated by Django 3.2.8 on 2021-11-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_magazine', '0035_auto_20210823_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='display_navbar',
            field=models.BooleanField(default=True),
        ),
    ]
