# Generated by Django 3.2.8 on 2021-12-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_magazine', '0036_topic_display_navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='displayed_in_navbars',
            field=models.BooleanField(default=True),
        ),
    ]
