# Generated by Django 3.2.18 on 2023-04-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_magazine', '0024_article_meta_category'),
        ('organization_magazine', '0037_topic_displayed_in_navbars'),
    ]

    operations = [
    ]
