# Generated by Django 3.2.19 on 2023-05-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_magazine', '0049_alter_article_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('_order',), 'verbose_name': 'article topic'},
        ),
    ]
