# Generated by Django 3.2.19 on 2023-08-23 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_magazine', '0055_auto_20230823_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['is_featured', '-updated', 'title'], 'permissions': (('user_add', 'Mezzo - User - User can add its own content'), ('user_edit', 'Mezzo - User - User can edit its own content'), ('user_delete', 'Mezzo - User - User can delete its own content'), ('team_add', "Mezzo - Team - User can add to his team's content"), ('team_edit', "Mezzo - Team - User can edit his team's content"), ('team_delete', "Mezzo - Team - User can delete his team's content")), 'verbose_name': 'article'},
        ),
    ]
