# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 12:51
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.pages.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20160725_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='in_menus',
            field=mezzanine.pages.fields.MenusField(blank=True, choices=[(1, 'Action'), (2, 'Departement'), (5, 'Magazine'), (3, 'Footer vertical'), (4, 'Footer horizontal')], max_length=100, null=True, verbose_name='Show in menus'),
        ),
    ]
