# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobresponse',
            name='message',
            field=models.TextField(default='', max_length=800, verbose_name='message'),
            preserve_default=False,
        ),
    ]
