# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-09-29 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_job', '0002_jobresponse_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
