# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization_job', '0004_candidacy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidacy',
            options={'verbose_name': 'candidacy', 'verbose_name_plural': 'candidacies'},
        ),
        migrations.AddField(
            model_name='candidacy',
            name='content_en',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='candidacy',
            name='content_fr',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='candidacy',
            name='text_button_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='text button'),
        ),
        migrations.AddField(
            model_name='candidacy',
            name='text_button_fr',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='text button'),
        ),
        migrations.AddField(
            model_name='candidacy',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='candidacy',
            name='title_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
    ]
