# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-11-07 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-job', '0012_auto_20170323_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidacy',
            name='slug',
            field=models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='slug',
            field=models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, verbose_name='URL'),
        ),
    ]
