# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-12-29 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-job', '0012_auto_20170323_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidacy',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='candidacy',
            name='text_button_external_fr',
        ),
        migrations.RemoveField(
            model_name='candidacy',
            name='text_button_internal_fr',
        ),
        migrations.RemoveField(
            model_name='candidacy',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='title_fr',
        ),
    ]
