# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-06-01 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_job', '0013_auto_20180403_1406'),
        ('organization_job', '0013_auto_20180307_1152'),
    ]

    operations = [
    ]
