# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-12 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-job', '0016_merge_20181116_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidacyimage',
            name='credits_fr',
        ),
        migrations.RemoveField(
            model_name='candidacyimage',
            name='title_fr',
        ),
    ]
