# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-18 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_job', '0022_auto_20190703_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidacy',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='candidacy',
            name='object_id',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='external_content',
            field=models.URLField(blank=True, max_length=1000, verbose_name='external content'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='text_button_external',
            field=models.CharField(blank=True, max_length=150, verbose_name='external text button'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='text_button_internal',
            field=models.CharField(blank=True, max_length=150, verbose_name='internal text button'),
        ),
    ]
