# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-08 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-job', '0022_auto_20190703_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidacy',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='candidacy',
            name='text_button_external_en',
        ),
        migrations.RemoveField(
            model_name='candidacy',
            name='text_button_internal_en',
        ),
        migrations.RemoveField(
            model_name='candidacy',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='candidacyimage',
            name='credits_en',
        ),
        migrations.RemoveField(
            model_name='candidacyimage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='title_en',
        ),
    ]
