# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-19 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-job', '0023_auto_20191218_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidacy',
            name='text_button_external',
        ),
        migrations.RemoveField(
            model_name='candidacy',
            name='text_button_external_en',
        ),
        migrations.RemoveField(
            model_name='candidacy',
            name='text_button_external_fr',
        ),
        migrations.RemoveField(
            model_name='candidacy',
            name='text_button_internal',
        ),
        migrations.RemoveField(
            model_name='candidacy',
            name='text_button_internal_en',
        ),
        migrations.RemoveField(
            model_name='candidacy',
            name='text_button_internal_fr',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='text_button_external',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='text_button_internal',
        ),
        migrations.AddField(
            model_name='candidacy',
            name='text_button',
            field=models.CharField(blank=True, max_length=150, verbose_name='text button'),
        ),
        migrations.AddField(
            model_name='candidacy',
            name='text_button_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='text button'),
        ),
        migrations.AddField(
            model_name='candidacy',
            name='text_button_fr',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='text button'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='text_button',
            field=models.CharField(blank=True, max_length=150, verbose_name='text button'),
        ),
    ]
