# Generated by Django 2.2.24 on 2021-08-23 15:53

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization-job', '0029_auto_20200616_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidacyimage',
            name='file',
            field=mezzanine.core.fields.FileField(max_length=1024, upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='jobofferimage',
            name='file',
            field=mezzanine.core.fields.FileField(max_length=1024, upload_to='images', verbose_name='Image'),
        ),
    ]
