# Generated by Django 3.2.18 on 2023-04-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_job', '0031_merge_0015_auto_20181002_1542_0030_auto_20210823_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidacyimage',
            name='type',
            field=models.CharField(choices=[('logo', 'logo'), ('logo_white', 'logo white'), ('logo_black', 'logo black'), ('logo_header', 'logo header'), ('logo_back', 'logo back'), ('logo_footer', 'logo footer'), ('slider', 'slider'), ('card', 'card'), ('page_slider', 'page - slider'), ('page_featured', 'page - featured'), ('hero', 'hero'), ('banner', 'banner')], max_length=64, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='jobofferimage',
            name='type',
            field=models.CharField(choices=[('logo', 'logo'), ('logo_white', 'logo white'), ('logo_black', 'logo black'), ('logo_header', 'logo header'), ('logo_back', 'logo back'), ('logo_footer', 'logo footer'), ('slider', 'slider'), ('card', 'card'), ('page_slider', 'page - slider'), ('page_featured', 'page - featured'), ('hero', 'hero'), ('banner', 'banner')], max_length=64, verbose_name='type'),
        ),
    ]
