# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpage',
            name='sub_title_en',
            field=models.TextField(blank=True, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='sub_title_fr',
            field=models.TextField(blank=True, null=True, verbose_name='sub title'),
        ),
    ]
