# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_auto_20160705_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpage',
            name='photo',
            field=mezzanine.core.fields.FileField(blank=True, max_length=1024, verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='photo_alignment',
            field=models.CharField(blank=True, choices=[('left', 'left'), ('right', 'right')], default='left', max_length=32, verbose_name='photo alignment'),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='photo_credits',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='photo credits'),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='photo_description',
            field=models.TextField(blank=True, verbose_name='photo description'),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='photo_featured',
            field=mezzanine.core.fields.FileField(blank=True, max_length=1024, verbose_name='photo featured'),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='photo_featured_credits',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='photo featured credits'),
        ),
    ]
