# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sub_title',
            field=models.TextField(blank=True, max_length=1000, verbose_name='sub title'),
        ),
    ]
