# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_auto_20160706_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'article'},
        ),
    ]
