# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_auto_20160706_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sub_title_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='sub_title_fr',
        ),
    ]
