# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0008_auto_20160706_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='sub_title',
            field=models.CharField(blank=True, max_length=1000, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sub_title_fr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='sub title'),
        ),
    ]
