# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('featured', '0001_initial'),
        ('organization media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='featured', to='organization media.Playlist', verbose_name='playlists'),
        ),
        migrations.AddField(
            model_name='featured',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='featured', to='organization media.Video', verbose_name='videos'),
        ),
    ]
