# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('structure', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='partners',
            field=models.ManyToManyField(to='structure.Organization', verbose_name='organizations'),
        ),
        migrations.AddField(
            model_name='project',
            name='persons',
            field=models.ManyToManyField(to='structure.Person', verbose_name='persons'),
        ),
        migrations.AddField(
            model_name='project',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
