# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-team', '0004_auto_20160715_1807'),
        ('organization-project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='partners',
        ),
        migrations.RemoveField(
            model_name='project',
            name='persons',
        ),
        migrations.AddField(
            model_name='project',
            name='leader_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_leader', to='organization-team.Team', verbose_name='lead team'),
        ),
        migrations.AddField(
            model_name='project',
            name='partner_organizations',
            field=models.ManyToManyField(blank=True, to='organization-team.Organization', verbose_name='partner organizations'),
        ),
        migrations.AddField(
            model_name='project',
            name='partner_persons',
            field=models.ManyToManyField(blank=True, to='organization-team.Person', verbose_name='partner persons'),
        ),
        migrations.AddField(
            model_name='project',
            name='partner_teams',
            field=models.ManyToManyField(blank=True, related_name='project_partners', to='organization-team.Team', verbose_name='partner teams'),
        ),
    ]
