# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 14:56
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization-project', '0005_auto_20160818_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectblock',
            options={'ordering': ('_order',)},
        ),
        migrations.AddField(
            model_name='projectblock',
            name='_order',
            field=mezzanine.core.fields.OrderField(null=True, verbose_name='Order'),
        ),
    ]
