# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0005_auto_20160229_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='photo_alignment',
            field=models.CharField(blank=True, choices=[('left', 'left'), ('right', 'right')], default='left', max_length=32, verbose_name='photo alignment'),
        ),
        migrations.AlterField(
            model_name='festivalevent',
            name='eve_event_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='eve id'),
        ),
        migrations.AlterField(
            model_name='video',
            name='media_id',
            field=models.CharField(max_length=128, verbose_name='media id'),
        ),
    ]
