# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0013_auto_20160407_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='poster',
            new_name='poster_url',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='poster',
            new_name='poster_url',
        ),
    ]
