# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20151223_1313'),
        ('pages', '0004_auto_20151223_1313'),
        ('mezzanine_agenda', '0006_remove_event_featured'),
        ('festival', '0014_auto_20160407_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='artist',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='video',
            name='featured',
        ),
        migrations.AddField(
            model_name='featured',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='featured', to='festival.Artist', verbose_name='artists'),
        ),
        migrations.AddField(
            model_name='featured',
            name='blogpost',
            field=models.ManyToManyField(blank=True, related_name='featured', to='blog.BlogPost', verbose_name='blog post'),
        ),
        migrations.AddField(
            model_name='featured',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='featured', to='mezzanine_agenda.Event', verbose_name='events'),
        ),
        migrations.AddField(
            model_name='featured',
            name='page',
            field=models.ManyToManyField(blank=True, related_name='featured', to='pages.Page', verbose_name='page'),
        ),
        migrations.AddField(
            model_name='featured',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='featured', to='festival.Playlist', verbose_name='playlists'),
        ),
        migrations.AddField(
            model_name='featured',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='featured', to='festival.Video', verbose_name='videos'),
        ),
    ]
