# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0020_auto_20160421_1059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageCategory',
        ),
    ]
