# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-08-26 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20160804_1547'),
        ('organization-media', '0002_auto_20160826_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAudio',
            fields=[
                ('audio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization-media.Audio')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audios', to='pages.Page', verbose_name='page')),
            ],
            options={
                'verbose_name_plural': 'audios',
                'verbose_name': 'audio',
            },
            bases=('organization-media.audio',),
        ),
        migrations.CreateModel(
            name='PageVideo',
            fields=[
                ('video_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization-media.Video')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='pages.Page', verbose_name='page')),
            ],
            options={
                'verbose_name_plural': 'videos',
                'verbose_name': 'video',
            },
            bases=('organization-media.video',),
        ),
        migrations.AlterOrderWithRespectTo(
            name='pagevideo',
            order_with_respect_to='page',
        ),
        migrations.AlterOrderWithRespectTo(
            name='pageaudio',
            order_with_respect_to='page',
        ),
    ]
