# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-08-26 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-media', '0003_auto_20160826_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='content',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='video',
            name='content',
        ),
        migrations.RemoveField(
            model_name='video',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='video',
            name='content_fr',
        ),
    ]
