# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-core', '0003_auto_20160825_1232'),
        ('organization-media', '0004_auto_20160826_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayableAudio',
            fields=[
                ('audio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization-media.Audio')),
                ('displayable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audios', to='organization-core.CustomDisplayable', verbose_name='displayable')),
            ],
            options={
                'verbose_name': 'audio',
                'verbose_name_plural': 'audios',
            },
            bases=('organization-media.audio',),
        ),
    ]
