# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-media', '0005_auto_20160930_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ('-created_at',), 'verbose_name': 'Audio', 'verbose_name_plural': 'Audios'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-created_at',), 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
