# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0005_auto_20160404_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='featured',
        ),
    ]
