# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0009_auto_20160410_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlocation',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='external_id'),
        ),
    ]
