# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20151223_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='placeholder_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Placeholder Text'),
        ),
        migrations.AlterField(
            model_name='field',
            name='placeholder_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Placeholder Text'),
        ),
        migrations.AlterField(
            model_name='field',
            name='placeholder_text_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Placeholder Text'),
        ),
    ]
