# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0006_remove_event_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='price')),
                ('unit', models.CharField(blank=True, max_length=16, verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Event price',
                'verbose_name_plural': 'Event pricies',
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('start',), 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='description',
            field=mezzanine.core.fields.RichTextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='link',
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='event',
            name='prices',
            field=models.ManyToManyField(blank=True, related_name='events', to='mezzanine_agenda.EventPrice', verbose_name='prices'),
        ),
    ]
