# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 19:49
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0007_auto_20160410_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlocation',
            name='description_en',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='description_fr',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
