# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0008_auto_20160410_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlocation',
            name='featured_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='fearured name'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
