# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0011_auto_20160410_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprice',
            name='unit',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Unit'),
        ),
    ]
