# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20151223_1313'),
        ('mezzanine_agenda', '0012_auto_20160410_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventprice',
            options={'ordering': ('-value',), 'verbose_name': 'Event price', 'verbose_name_plural': 'Event pricies'},
        ),
        migrations.AddField(
            model_name='event',
            name='blog_posts',
            field=models.ManyToManyField(blank=True, related_name='events', to='blog.BlogPost', verbose_name='blog posts'),
        ),
    ]
