# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 13:56
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0013_auto_20160510_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='brochure',
            field=mezzanine.core.fields.FileField(blank=True, max_length=1024, verbose_name='brochure'),
        ),
    ]
