# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicpage',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='photo_alignment',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='photo_card',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='photo_card_credits',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='photo_credits',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='photo_description',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='photo_slider',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='photo_slider_credits',
        ),
    ]
