# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_core', '0002_linktype_picto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linktype',
            name='picto',
        ),
    ]
