# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-core', '0003_auto_20160825_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdisplayable',
            name='site',
        ),
        migrations.RemoveField(
            model_name='displayableblock',
            name='displayable',
        ),
        migrations.RemoveField(
            model_name='displayableimage',
            name='displayable',
        ),
        migrations.RemoveField(
            model_name='displayablelink',
            name='displayable',
        ),
        migrations.RemoveField(
            model_name='displayablelink',
            name='link_type',
        ),
        migrations.RemoveField(
            model_name='modelblock',
            name='model',
        ),
        migrations.RemoveField(
            model_name='modelimage',
            name='model',
        ),
        migrations.RemoveField(
            model_name='modellink',
            name='link_type',
        ),
        migrations.RemoveField(
            model_name='modellink',
            name='model',
        ),
    ]
