# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-14 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_core', '0004_auto_20160923_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='linktype',
            name='fa_option',
            field=models.CharField(blank=True, help_text='will be added to fa-<slug>', max_length=64, null=True, verbose_name='fontawesome icon name option'),
        ),
    ]
