# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-core', '0004_auto_20160725_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='title_en',
            field=models.CharField(max_length=1024, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='title_fr',
            field=models.CharField(max_length=1024, null=True, verbose_name='title'),
        ),
    ]
