# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-core', '0006_pageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='photo description'),
        ),
        migrations.AddField(
            model_name='pageimage',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='photo description'),
        ),
    ]
