# Generated by Django 3.2.19 on 2023-05-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_core', '0008_auto_20230523_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metacategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
