# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-core', '0008_auto_20160727_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblock',
            name='with_separator',
            field=models.BooleanField(default=False),
        ),
    ]
