# Generated by Django 3.2.19 on 2023-06-01 14:35

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization_core', '0010_auto_20230601_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metacategory',
            name='logo',
            field=mezzanine.core.fields.FileField(blank=True, max_length=1024, null=True, verbose_name='Image'),
        ),
    ]
