# Generated by Django 3.2.19 on 2023-06-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_core', '0011_alter_metacategory_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metacategory',
            name='logo',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to='images', verbose_name='Image'),
        ),
    ]
