# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-core', '0012_auto_20160818_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
