# Generated by Django 3.2.19 on 2023-09-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_core', '0014_metacategory_icon_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metacategory',
            options={'ordering': ['order'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='metacategory',
            name='_order',
        ),
        migrations.AddField(
            model_name='metacategory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
    ]
