# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-08-26 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-core', '0003_auto_20160825_1232'),
        ('organization-media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='_meta_title',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='created',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='description',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='gen_description',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='in_sitemap',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='keywords_string',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='short_url',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='site',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='status',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='title',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='video',
            name='_meta_title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='created',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='video',
            name='gen_description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='in_sitemap',
        ),
        migrations.RemoveField(
            model_name='video',
            name='keywords_string',
        ),
        migrations.RemoveField(
            model_name='video',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='video',
            name='short_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='site',
        ),
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='video',
            name='status',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='updated',
        ),
        migrations.AddField(
            model_name='audio',
            name='customdisplayable_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization-core.CustomDisplayable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='customdisplayable_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization-core.CustomDisplayable'),
            preserve_default=False,
        ),
    ]
