# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_media', '0004_auto_20161007_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ('-created_at',), 'verbose_name': 'audio'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-created_at',), 'verbose_name': 'video'},
        ),
    ]
