# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_media', '0009_auto_20161013_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='type',
            field=models.CharField(choices=[('audio', 'audio'), ('video', 'video')], max_length=32, verbose_name='type'),
        ),
    ]
