# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 09:36
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization_media', '0010_auto_20161014_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediatranscoded',
            name='file',
            field=mezzanine.core.fields.FileField(blank=True, max_length=1024, null=True, verbose_name='file'),
        ),
    ]
