# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-28 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_media', '0011_auto_20161014_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistrelated',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist_related', to='organization_media.Playlist', verbose_name='playlist'),
        ),
    ]
