# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-14 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0017_auto_20170222_1039'),
        ('organization-media', '0014_livestreaming'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestreaming',
            name='event_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_streaming_location', to='mezzanine_agenda.EventLocation', verbose_name='Event Location'),
        ),
    ]
