# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-12-29 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-media', '0015_livestreaming_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestreaming',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='livestreaming',
            name='html5_url_fr',
        ),
        migrations.RemoveField(
            model_name='livestreaming',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='media',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='media',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='mediacategory',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='mediacategory',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='title_fr',
        ),
    ]
