# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-24 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-media', '0016_auto_20180307_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestreaming',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='livestreaming',
            name='html5_url_fr',
        ),
        migrations.RemoveField(
            model_name='livestreaming',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='media',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='media',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='mediacategory',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='mediacategory',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='title_fr',
        ),
    ]
