# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-08 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-media', '0025_auto_20190703_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestreaming',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='livestreaming',
            name='html5_url_en',
        ),
        migrations.RemoveField(
            model_name='livestreaming',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='media',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='media',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='mediacategory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='mediacategory',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='mediaimage',
            name='credits_en',
        ),
        migrations.RemoveField(
            model_name='mediaimage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='title_en',
        ),
    ]
