# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-12-19 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-media', '0026_auto_20201026_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='iframe',
            field=models.TextField(blank=True, verbose_name='Iframe'),
        ),
    ]
