# Generated by Django 3.2.18 on 2023-04-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_media', '0018_auto_20181002_1542'),
        ('organization_media', '0028_auto_20210823_1753'),
    ]

    operations = [
    ]
