# Generated by Django 3.2.18 on 2023-04-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_media', '0019_auto_20230424_1520'),
        ('organization_media', '0029_merge_0018_auto_20181002_1542_0028_auto_20210823_1753'),
    ]

    operations = [
    ]
