# Generated by Django 3.2.19 on 2023-06-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_media', '0031_auto_20230601_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaimage',
            name='title',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='title_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='title_fr',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='title'),
        ),
    ]
