# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 16:21
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization-pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamiccontenthomeslider',
            options={'ordering': ('_order',), 'verbose_name': 'Dynamic Content Home Slider'},
        ),
        migrations.AddField(
            model_name='dynamiccontenthomeslider',
            name='_order',
            field=mezzanine.core.fields.OrderField(null=True, verbose_name='Order'),
        ),
    ]
