# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20160923_1219'),
        ('organization_pages', '0002_auto_20160914_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', mezzanine.core.fields.FileField(max_length=1024, verbose_name='Image')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_images', to='pages.Link', verbose_name='link')),
            ],
            options={
                'verbose_name': 'link image',
                'verbose_name_plural': 'link images',
            },
        ),
        migrations.AlterOrderWithRespectTo(
            name='linkimage',
            order_with_respect_to='link',
        ),
    ]
