# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-pages', '0002_joboffer_jobresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='title_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
    ]
