# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-pages', '0002_auto_20160824_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='pages.Page', verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='pageimage',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='pages.Page', verbose_name='page'),
        ),
    ]
