# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 09:53
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization-pages', '0003_auto_20160907_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joboffer',
            options={'verbose_name': 'job offer', 'verbose_name_plural': 'job offers'},
        ),
        migrations.AddField(
            model_name='joboffer',
            name='content',
            field=mezzanine.core.fields.RichTextField(default='', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
