# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-07 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pages', '0005_auto_20160923_1219'),
        ('organization_pages', '0004_auto_20160928_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicContentPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('object_id', models.PositiveIntegerField(editable=False, null=True, verbose_name='related object')),
                ('content_type', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_content_pages', to='pages.Page', verbose_name='page')),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Dynamic Content Page',
            },
        ),
    ]
