# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-07 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organization_pages', '0005_dynamiccontentpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicContentHomeMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('object_id', models.PositiveIntegerField(editable=False, null=True, verbose_name='related object')),
                ('content_type', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type')),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization_pages.Home', verbose_name='home')),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Media',
            },
        ),
        migrations.AlterModelOptions(
            name='dynamiccontenthomebody',
            options={'ordering': ('_order',), 'verbose_name': 'Body'},
        ),
        migrations.AlterModelOptions(
            name='dynamiccontenthomeslider',
            options={'ordering': ('_order',), 'verbose_name': 'Slider'},
        ),
    ]
