# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-pages', '0007_auto_20160908_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobresponse',
            name='site',
        ),
        migrations.RemoveField(
            model_name='jobresponse',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='jobresponse',
            name='title',
        ),
    ]
