# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_pages', '0009_auto_20161014_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='title_en',
            field=models.CharField(max_length=1024, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='pageimage',
            name='title_fr',
            field=models.CharField(max_length=1024, null=True, verbose_name='title'),
        ),
    ]
