# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_pages', '0011_pagelink_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblock',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
