# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-28 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20160923_1219'),
        ('organization_pages', '0013_auto_20161026_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageRelatedTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1024, null=True, verbose_name='title')),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_title', to='pages.Page', verbose_name='page')),
            ],
            options={
                'verbose_name': 'related title',
            },
        ),
        migrations.AlterOrderWithRespectTo(
            name='pagerelatedtitle',
            order_with_respect_to='page',
        ),
    ]
