# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-15 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-pages', '0018_auto_20170105_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='menu_alinea',
            field=models.BooleanField(default=False, verbose_name='menu alinea'),
        ),
    ]
