# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-11 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-pages', '0019_custompage_menu_alinea'),
        ('organization-pages', '0020_homeimage'),
    ]

    operations = [
    ]
