# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-07-20 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20170223_2352'),
        ('organization-pages', '0021_homeimage_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='VertigoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('sub_title', models.TextField(blank=True, max_length=1024, verbose_name='sub title')),
            ],
            options={
                'verbose_name': 'vertigo page',
                'ordering': ('_order',),
            },
            bases=('pages.page', models.Model),
        ),
    ]
