# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-27 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-pages', '0021_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='background_color',
            field=models.CharField(blank=True, choices=[('black', 'black'), ('yellow', 'yellow'), ('red', 'red'), ('white', 'white'), ('blue', 'blue'), ('purple', 'purple')], max_length=32, verbose_name='background color'),
        ),
    ]
