# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-07-20 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization-pages', '0022_vertigopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vertigopage',
            name='content_en',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='vertigopage',
            name='content_fr',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='vertigopage',
            name='sub_title_en',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='vertigopage',
            name='sub_title_fr',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='sub title'),
        ),
    ]
