# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-26 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_pages', '0022_auto_20170427_1211'),
        ('organization_pages', '0022_extendedcustompage_extendedcustompagedynamiccontent'),
        ('organization_pages', '0020_auto_20170823_1825'),
    ]

    operations = [
    ]
