# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-08-22 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-pages', '0023_auto_20170720_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='VertigoPageDynamicContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_content', models.IntegerField(choices=[(0, 'No extra content'), (1, 'List of News'), (2, 'List of Events')], default=0)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_content', to='organization-pages.VertigoPage', verbose_name='vertigo page')),
            ],
        ),
    ]
