# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-08-30 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-pages', '0024_vertigopagedynamiccontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vertigopagedynamiccontent',
            name='extra_content',
            field=models.CharField(choices=[('none', 'No extra content'), ('news', 'List of News'), ('events', 'List of Events'), ('jury', 'List of the Jury')], default='none', max_length=32),
        ),
    ]
