# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-12-22 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_pages', '0024_auto_20171221_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamiccontenthomebody',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization_pages.Home', verbose_name='home'),
        ),
        migrations.AlterField(
            model_name='dynamiccontenthomemedia',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_content_home_media', to='organization_pages.Home', verbose_name='home'),
        ),
        migrations.AlterField(
            model_name='dynamiccontenthomeslider',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization_pages.Home', verbose_name='home'),
        ),
    ]
