# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-12-29 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-pages', '0024_auto_20171221_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompage',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='custompage',
            name='sub_title_fr',
        ),
        migrations.RemoveField(
            model_name='extendedcustompage',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='extendedcustompage',
            name='sub_title_fr',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='pageimage',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='pageimage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='pagelink',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='pagerelatedtitle',
            name='title_fr',
        ),
    ]
