# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-03-07 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-pages', '0026_auto_20180307_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkstyle',
            name='link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_style', to='pages.Link', verbose_name='link'),
        ),
    ]
