# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-03-07 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-pages', '0027_auto_20180307_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='class_css',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
