# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-05-29 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_pages', '0028_custompage_class_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompage',
            name='class_css',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='CSS class'),
        ),
        migrations.AlterField(
            model_name='linkstyle',
            name='class_css',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='CSS class'),
        ),
    ]
