# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-06-15 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-pages', '0029_auto_20180529_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedcustompagedynamiccontent',
            name='extra_content',
            field=models.CharField(choices=[('none', 'No extra content'), ('news', 'List of News'), ('events', 'List of Events'), ('jury', 'List of the Jury'), ('producers', 'List of Producers')], default='none', max_length=32),
        ),
    ]
