# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-24 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-pages', '0030_auto_20180615_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompage',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='custompage',
            name='sub_title_fr',
        ),
        migrations.RemoveField(
            model_name='extendedcustompage',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='extendedcustompage',
            name='sub_title_fr',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='pageimage',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='pageimage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='pagelink',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='pagerelatedtitle',
            name='title_fr',
        ),
    ]
