# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-23 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_pages', '0032_auto_20190117_1158'),
        ('organization_pages', '0032_auto_20181227_1252'),
    ]

    operations = [
    ]
