# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-16 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-pages', '0030_auto_20181102_1151'),
        ('organization-pages', '0032_auto_20181105_2349'),
    ]

    operations = [
    ]
