# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-19 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_pages', '0034_auto_20190130_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompage',
            options={'ordering': ('_order',)},
        ),
    ]
