# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-06 16:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization-pages', '0034_auto_20190130_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='custompages', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
            preserve_default=False,
        ),
    ]
