# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-07 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-pages', '0041_auto_20190703_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='block_order',
            field=models.CharField(default='0,1,2,3,4,5,6,7', max_length=32, verbose_name='\n        order of blocks (\n            0: blocks,\n            1: images,\n            2: playlists,\n            3: multimedias,\n            4: liens,\n            5: liste de personnes,\n            6: listes des produits,\n            7: Titre de contenu liés\n            8: Dynamic Content pages\n        )\n        '),
        ),
    ]
