# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-08 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-pages', '0041_auto_20190703_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompage',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='custompage',
            name='sub_title_en',
        ),
        migrations.RemoveField(
            model_name='extendedcustompage',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='extendedcustompage',
            name='sub_title_en',
        ),
        migrations.RemoveField(
            model_name='homeimage',
            name='credits_en',
        ),
        migrations.RemoveField(
            model_name='homeimage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='pageblock',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='pageimage',
            name='credits_en',
        ),
        migrations.RemoveField(
            model_name='pageimage',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='pageimage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='pagelink',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='pagerelatedtitle',
            name='title_en',
        ),
    ]
