# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-10 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_pages', '0042_auto_20210823_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='block_order',
            field=models.CharField(default='0,1,2,3,4,5', max_length=32, verbose_name='\n        order of blocks (\n            0: images,\n            1: multimedias,\n            2: liste de personnes,\n            3: blocks,\n            4: listes des produits,\n            5: Dynamic Content pages\n        )\n        '),
        ),
    ]
