# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-14 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_pages', '0042_custompage_block_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='separator',
            field=models.CharField(default='0,0,1,1,1,1', max_length=32, verbose_name='\n        separator before blocks,\n        0 : no sepeartor\n        1 : separator\n\n        order of blocks (\n            0: images,\n            1: multimedias,\n            2: liste de personnes,\n            3: blocks,\n            4: listes des produits,\n            5: Dynamic Content pages\n        )\n        \n        '),
        ),
    ]
