# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-14 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_pages', '0045_pagerelatedtitle_display_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagerelatedtitle',
            name='display_mode',
            field=models.CharField(choices=[('0', 'Affichage toute largueur'), ('1', 'Affichage pour menu gauche')], default='0', max_length=1),
        ),
    ]
