# Generated by Django 3.2.8 on 2021-11-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_pages', '0048_auto_20211122_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagerelatedtitle',
            name='as_page_title',
            field=models.BooleanField(default=False, verbose_name='Afficher le titre comme un titre de page'),
        ),
    ]
