# Generated by Django 3.2.8 on 2021-11-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_pages', '0049_pagerelatedtitle_as_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='display_navbar',
            field=models.BooleanField(default=True),
        ),
    ]
