# Generated by Django 3.2.18 on 2023-04-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_pages', '0031_auto_20181002_1542'),
        ('organization_pages', '0051_custompage_displayed_in_navbars'),
    ]

    operations = [
    ]
