# Generated by Django 3.2.18 on 2023-04-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_pages', '0052_merge_20230424_1820'),
    ]

    operations = [
    ]
