# Generated by Django 3.2.19 on 2023-06-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_pages', '0055_auto_20230601_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='punchline',
            field=models.TextField(blank=True, null=True, verbose_name='Punchline'),
        ),
    ]
