# Generated by Django 3.2.19 on 2023-08-25 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_page_in_menus'),
        ('organization_pages', '0057_auto_20230602_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
                ('name_fr', models.CharField(max_length=512, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=512, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='pages.page', verbose_name='page')),
            ],
            options={
                'verbose_name': 'action',
                'verbose_name_plural': 'action',
                'order_with_respect_to': 'page',
            },
        ),
    ]
