        # Generated by Django 3.2.19 on 2023-08-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_pages', '0058_pageaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageaction',
            name='action',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='action'),
        ),
        migrations.AddField(
            model_name='pageaction',
            name='action_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='action'),
        ),
        migrations.AddField(
            model_name='pageaction',
            name='action_fr',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='action'),
        ),
    ]
