# Generated by Django 3.2.19 on 2023-08-29 14:30

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization_pages', '0059_auto_20230825_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageaction',
            name='credits',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='credits'),
        ),
        migrations.AddField(
            model_name='pageaction',
            name='crop_data',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='pageaction',
            name='file',
            field=mezzanine.core.fields.FileField(blank=True, max_length=1024, null=True, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='pageaction',
            name='type',
            field=models.CharField(blank=True, choices=[('logo', 'logo'), ('logo_white', 'logo white'), ('logo_black', 'logo black'), ('logo_header', 'logo header'), ('logo_back', 'logo back'), ('logo_footer', 'logo footer'), ('slider', 'slider'), ('card', 'card'), ('page_slider', 'page - slider'), ('page_featured', 'page - featured'), ('hero', 'hero'), ('banner', 'banner')], max_length=64, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='pageaction',
            name='url',
            field=models.URLField(blank=True, max_length=512, verbose_name='URL'),
        ),
    ]
