# Generated by Django 3.2.19 on 2023-09-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_pages', '0061_pageaction_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageaction',
            name='hex_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='color hexa code'),
        ),
    ]
