# Generated by Django 3.2.19 on 2023-09-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_pages', '0062_pageaction_hex_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='punchline_en',
            field=models.TextField(blank=True, null=True, verbose_name='Punchline'),
        ),
        migrations.AddField(
            model_name='home',
            name='punchline_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Punchline'),
        ),
    ]
