# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0005_auto_20160905_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationaudio',
            old_name='project',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='organizationblock',
            old_name='project',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='organizationimage',
            old_name='project',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='organizationlink',
            old_name='project',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='organizationvideo',
            old_name='project',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='personaudio',
            old_name='project',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='personblock',
            old_name='project',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='personimage',
            old_name='project',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='personlink',
            old_name='project',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='personvideo',
            old_name='project',
            new_name='person',
        ),
    ]
