# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20160804_1547'),
        ('organization-network', '0008_auto_20160916_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='personlistblock',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_list_block', to='pages.Page', verbose_name='Page'),
        ),
    ]
