# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0009_personlistblock_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonAutocomplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_list_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_autocomplete', to='organization-network.PersonListBlock', verbose_name='Person List Block')),
            ],
            options={
                'verbose_name': 'Person autocomplete',
            },
        ),
    ]
