# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0011_personautocomplete_persons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personautocomplete',
            old_name='persons',
            new_name='person',
        ),
    ]
