# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0012_auto_20160916_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personautocomplete',
            name='person',
        ),
        migrations.AddField(
            model_name='personlistblock',
            name='persons',
            field=models.ManyToManyField(to='organization-network.Person'),
        ),
    ]
