# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0013_auto_20160919_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personlistblockinline',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_list_block_inline', to='organization_network.Person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='personlistblockinline',
            name='person_list_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_list_block_inline', to='organization_network.PersonListBlock', verbose_name='Person List Block'),
        ),
    ]
