# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0014_auto_20160916_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personautocomplete',
            name='person',
        ),
        migrations.AddField(
            model_name='personlistblock',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization-network.Person'),
            preserve_default=False,
        ),
    ]
