# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0017_personlistblock_person_list_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personlistblock',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personlistblock',
            name='person_list_block',
        ),
        migrations.AddField(
            model_name='personautocomplete',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_list_block', to='organization-network.Person', verbose_name='Person'),
        ),
    ]
