# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0020_auto_20160921_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personactivity',
            old_name='date_begin',
            new_name='date_from',
        ),
        migrations.RenameField(
            model_name='personactivity',
            old_name='date_end',
            new_name='date_to',
        ),
    ]
