# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-03 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0026_auto_20160929_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='personactivity',
            name='second_team_text',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='second team text'),
        ),
    ]
