# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-04 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0027_personactivity_second_team_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_legacy',
            field=models.BooleanField(default=False, verbose_name='is legacy'),
        ),
    ]
