# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0030_team_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='is_on_map',
            field=models.BooleanField(default=False, verbose_name='is on map'),
        ),
    ]
