# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0033_auto_20161005_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='city'),
        ),
    ]
