# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0035_auto_20161005_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(max_length=255, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(max_length=16, verbose_name='postal code'),
        ),
    ]
