# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_media', '0006_auto_20161013_1631'),
        ('organization_network', '0037_organizationtype_css_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPlaylist',
            fields=[
                ('playlist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization_media.Playlist')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to='organization_network.Organization', verbose_name='organization')),
            ],
            options={
                'abstract': False,
            },
            bases=('organization_media.playlist',),
        ),
        migrations.CreateModel(
            name='PersonPlaylist',
            fields=[
                ('playlist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization_media.Playlist')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to='organization_network.Person', verbose_name='person')),
            ],
            options={
                'abstract': False,
            },
            bases=('organization_media.playlist',),
        ),
        migrations.RemoveField(
            model_name='organizationaudio',
            name='audio_ptr',
        ),
        migrations.RemoveField(
            model_name='organizationaudio',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationvideo',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationvideo',
            name='video_ptr',
        ),
        migrations.RemoveField(
            model_name='personaudio',
            name='audio_ptr',
        ),
        migrations.RemoveField(
            model_name='personaudio',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personvideo',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personvideo',
            name='video_ptr',
        ),
        migrations.DeleteModel(
            name='OrganizationAudio',
        ),
        migrations.DeleteModel(
            name='OrganizationVideo',
        ),
        migrations.DeleteModel(
            name='PersonAudio',
        ),
        migrations.DeleteModel(
            name='PersonVideo',
        ),
    ]
