# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-18 10:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0039_auto_20161014_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='person',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='personlistblock',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 18, 12, 3, 24, 592756), verbose_name='creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personlistblock',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 18, 12, 3, 30, 482037), verbose_name='last modification date'),
            preserve_default=False,
        ),
    ]
