# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0043_auto_20161021_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='personactivity',
            name='phd_officer_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phd_officer_3_activity', to='organization_network.Person', verbose_name='PhD officer 3'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='third_employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_employer_activity', to='organization_network.Organization', verbose_name='third employer'),
        ),
    ]
