# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0022_projectlink_title'),
        ('organization_network', '0044_auto_20161021_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personactivity',
            name='phd_director',
        ),
        migrations.RemoveField(
            model_name='personactivity',
            name='phd_officer_1',
        ),
        migrations.RemoveField(
            model_name='personactivity',
            name='phd_officer_2',
        ),
        migrations.RemoveField(
            model_name='personactivity',
            name='phd_officer_3',
        ),
        migrations.RemoveField(
            model_name='personactivity',
            name='project',
        ),
        migrations.AddField(
            model_name='organization',
            name='initials',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='initials'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='phd_directors',
            field=models.ManyToManyField(blank=True, related_name='phd_director_activities', to='organization_network.Person', verbose_name='PhD directors'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='phd_officers',
            field=models.ManyToManyField(blank=True, related_name='phd_officer_activities', to='organization_network.Person', verbose_name='PhD officers'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='activities', to='organization_projects.Project', verbose_name='projects'),
        ),
        migrations.AlterField(
            model_name='personactivity',
            name='attachment_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachment_activities', to='organization_network.Organization', verbose_name='attachment organization'),
        ),
        migrations.AlterField(
            model_name='personactivity',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_activities', to='organization_network.Organization', verbose_name='employer'),
        ),
        migrations.AlterField(
            model_name='personactivity',
            name='second_employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_employer_activities', to='organization_network.Organization', verbose_name='second employer'),
        ),
        migrations.AlterField(
            model_name='personactivity',
            name='second_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_team_activities', to='organization_network.Team', verbose_name='second team'),
        ),
        migrations.AlterField(
            model_name='personactivity',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_activities', to='organization_network.Team', verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='personactivity',
            name='third_employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_employer_activities', to='organization_network.Organization', verbose_name='third employer'),
        ),
    ]
