# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-04 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0047_auto_20161104_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='mappable_location',
            field=models.CharField(blank=True, help_text='This address will be used to calculate latitude and longitude. Leave blank and set Latitude and Longitude to specify the location yourself, or leave all three blank to auto-fill from the Location field.', max_length=128, null=True),
        ),
    ]
