# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-04 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0048_auto_20161104_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personactivity',
            name='organization',
        ),
        migrations.AddField(
            model_name='personactivity',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='project_activities', to='organization_network.Organization', verbose_name='organizations (attachment or subscribed)'),
        ),
    ]
