# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-06 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0049_auto_20161104_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitystatus',
            options={'ordering': ['-order'], 'verbose_name': 'activity status'},
        ),
        migrations.AlterModelOptions(
            name='personactivity',
            options={'ordering': ['person__last_name'], 'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
        migrations.AddField(
            model_name='activitystatus',
            name='display',
            field=models.BooleanField(default=False, verbose_name='display on team page'),
        ),
        migrations.AddField(
            model_name='activitystatus',
            name='order',
            field=models.IntegerField(default=1, verbose_name='order number'),
        ),
    ]
