# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-06 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0050_auto_20161106_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personactivity',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='organization_network.ActivityStatus', verbose_name='status'),
        ),
    ]
