# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-06 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0051_auto_20161106_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitystatus',
            options={'ordering': ['order'], 'verbose_name': 'activity status'},
        ),
        migrations.AlterField(
            model_name='activitystatus',
            name='order',
            field=models.IntegerField(default=100, verbose_name='order number'),
        ),
    ]
