# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-07 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0052_auto_20161106_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystatus',
            name='display',
            field=models.BooleanField(default=True, verbose_name='display on team page'),
        ),
    ]
