# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-08 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0056_auto_20161108_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystatus',
            name='display_text_en',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='display text'),
        ),
        migrations.AddField(
            model_name='activitystatus',
            name='display_text_fr',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='display text'),
        ),
    ]
