# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-13 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0058_auto_20161109_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityStatusFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
                ('name_fr', models.CharField(max_length=512, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=512, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('order', models.IntegerField(default=100, verbose_name='order number')),
                ('display', models.BooleanField(default=True, verbose_name='display on team page')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Status family',
            },
        ),
        migrations.AlterModelOptions(
            name='activityframework',
            options={'verbose_name': 'framework', 'verbose_name_plural': 'frameworks'},
        ),
        migrations.AlterModelOptions(
            name='activityfunction',
            options={'verbose_name': 'function', 'verbose_name_plural': 'functions'},
        ),
        migrations.AlterModelOptions(
            name='activitygrade',
            options={'verbose_name': 'grade', 'verbose_name_plural': 'grades'},
        ),
        migrations.AlterModelOptions(
            name='activitystatus',
            options={'ordering': ['order'], 'verbose_name': 'status'},
        ),
        migrations.AlterModelOptions(
            name='budgetcode',
            options={'verbose_name': 'budget code', 'verbose_name_plural': 'budget codes'},
        ),
        migrations.AlterModelOptions(
            name='recordpiece',
            options={'verbose_name': 'record piece', 'verbose_name_plural': 'record pieces'},
        ),
        migrations.AlterModelOptions(
            name='traininglevel',
            options={'verbose_name': 'training level', 'verbose_name_plural': 'training levels'},
        ),
        migrations.AlterModelOptions(
            name='trainingspeciality',
            options={'verbose_name': 'training speciality', 'verbose_name_plural': 'training specialities'},
        ),
        migrations.AlterModelOptions(
            name='trainingtopic',
            options={'verbose_name': 'training topic', 'verbose_name_plural': 'training topics'},
        ),
        migrations.AlterModelOptions(
            name='trainingtype',
            options={'verbose_name': 'training type', 'verbose_name_plural': 'training types'},
        ),
        migrations.RemoveField(
            model_name='activitystatus',
            name='display_text',
        ),
        migrations.RemoveField(
            model_name='activitystatus',
            name='display_text_en',
        ),
        migrations.RemoveField(
            model_name='activitystatus',
            name='display_text_fr',
        ),
        migrations.AddField(
            model_name='organization',
            name='opening_times',
            field=models.TextField(blank=True, verbose_name='opening times'),
        ),
        migrations.AddField(
            model_name='organization',
            name='subway_access',
            field=models.TextField(blank=True, verbose_name='subway access'),
        ),
        migrations.AddField(
            model_name='organization',
            name='telephone',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='telephone'),
        ),
        migrations.AddField(
            model_name='person',
            name='telephone',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='telephone'),
        ),
        migrations.AddField(
            model_name='activitystatus',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_statuses', to='organization_network.ActivityStatusFamily', verbose_name='family'),
        ),
    ]
