# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-14 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0060_auto_20161113_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitystatus',
            name='family',
        ),
        migrations.AddField(
            model_name='activitystatus',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organization_network.ActivityStatus', verbose_name='parent'),
        ),
        migrations.DeleteModel(
            name='ActivityStatusFamily',
        ),
    ]
