# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-16 15:06
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0066_auto_20161216_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationservice',
            options={'ordering': ('_order',)},
        ),
        migrations.AddField(
            model_name='organizationservice',
            name='_order',
            field=mezzanine.core.fields.OrderField(null=True, verbose_name='Order'),
        ),
    ]
