# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-16 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0068_auto_20161216_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationservice',
            name='css_banner_type',
            field=models.CharField(blank=True, choices=[('fsxxl', 'fsxxl'), ('fsxxxl', 'fsxxxl')], max_length=64, null=True, verbose_name='css banner type'),
        ),
        migrations.AlterField(
            model_name='organizationservice',
            name='css_color',
            field=models.CharField(blank=True, choices=[('orange', 'orange'), ('blue', 'blue'), ('green', 'green')], max_length=64, null=True, verbose_name='css color'),
        ),
    ]
