# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-22 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0070_auto_20161222_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personactivityweeklyhourvolume',
            name='activity',
        ),
        migrations.AddField(
            model_name='personactivity',
            name='friday_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='friday hours'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='monday_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='monday hours'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='thursday_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='thursday hours'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='tuesday_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='tuesday hours'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='wednesday_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='wednesday hours'),
        ),
        migrations.DeleteModel(
            name='PersonActivityWeeklyHourVolume',
        ),
    ]
