# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-22 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0071_auto_20161222_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityweeklyhourvolume',
            name='friday_hours',
            field=models.FloatField(verbose_name='friday hours'),
        ),
        migrations.AlterField(
            model_name='activityweeklyhourvolume',
            name='monday_hours',
            field=models.FloatField(verbose_name='monday hours'),
        ),
        migrations.AlterField(
            model_name='activityweeklyhourvolume',
            name='thursday_hours',
            field=models.FloatField(verbose_name='thursday hours'),
        ),
        migrations.AlterField(
            model_name='activityweeklyhourvolume',
            name='tuesday_hours',
            field=models.FloatField(verbose_name='tuesday hours'),
        ),
        migrations.AlterField(
            model_name='activityweeklyhourvolume',
            name='wednesday_hours',
            field=models.FloatField(verbose_name='wednesday hours'),
        ),
        migrations.AlterField(
            model_name='personactivity',
            name='friday_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='friday hours'),
        ),
        migrations.AlterField(
            model_name='personactivity',
            name='monday_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='monday hours'),
        ),
        migrations.AlterField(
            model_name='personactivity',
            name='thursday_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='thursday hours'),
        ),
        migrations.AlterField(
            model_name='personactivity',
            name='tuesday_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='tuesday hours'),
        ),
        migrations.AlterField(
            model_name='personactivity',
            name='wednesday_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='wednesday hours'),
        ),
    ]
