# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-28 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0033_projectworkpackage'),
        ('organization-network', '0073_auto_20161228_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='personactivitytimesheet',
            name='work_packages',
            field=models.ManyToManyField(blank=True, related_name='timesheets', to='organization-projects.ProjectWorkPackage', verbose_name='work package'),
        ),
    ]
