# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-30 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import organization.network.validators


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0075_auto_20161229_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personactivitytimesheet',
            name='percentage',
            field=models.FloatField(validators=[organization.network.validators.validate_positive], verbose_name='% of work time on the project'),
        ),
    ]
