# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-04 17:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0076_auto_20161230_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='personactivitytimesheet',
            name='accounting',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 1, 4, 17, 35, 33, 228164, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='personactivitytimesheet',
            name='validation',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 1, 4, 17, 35, 33, 228198, tzinfo=utc)),
        ),
    ]
