# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-11 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0078_auto_20170105_1743'),
        ('organization-network', '0081_auto_20170106_1645'),
    ]

    operations = [
    ]
