# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-16 11:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0082_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personactivitytimesheet',
            name='accounting',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 1, 16, 11, 33, 2, 772761, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='personactivitytimesheet',
            name='validation',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 1, 16, 11, 33, 2, 772794, tzinfo=utc), null=True),
        ),
    ]
