# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-27 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields
import organization.network.validators


class Migration(migrations.Migration):

    dependencies = [
        ('organization-projects', '0042_auto_20170118_1239'),
        ('organization-network', '0086_auto_20170118_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('title', models.CharField(max_length=1024, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('default_percentage', models.FloatField(blank=True, null=True, validators=[organization.network.validators.validate_positive], verbose_name='default %')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_activity', to='organization-network.PersonActivity', verbose_name='activity')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activity', to='organization-projects.Project', verbose_name='project')),
                ('work_packages', models.ManyToManyField(blank=True, related_name='project_activity', to='organization-projects.ProjectWorkPackage', verbose_name='work package')),
            ],
            options={
                'verbose_name_plural': 'project activities',
                'ordering': ('_order',),
                'verbose_name': 'project activity',
            },
        ),
        migrations.AlterUniqueTogether(
            name='projectactivity',
            unique_together=set([('project', 'default_percentage')]),
        ),
    ]
