# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-23 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('organization-network', '0087_auto_20170214_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site'),
        ),
    ]
