# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-30 15:34
from __future__ import unicode_literals

from django.db import migrations, models
from organization.network.models import PersonActivityTimeSheet

def migrate_percentage(apps, schema_editor):
    pats = PersonActivityTimeSheet.objects.all()
    for pat in pats :
        pat.percentage = pat.percentage * 100
        pat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0089_auto_20170127_1933'),
    ]

    operations = [
    	migrations.RunPython(migrate_percentage),
    ]
