# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-13 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0089_auto_20170303_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization-network.Person')),
            ],
            options={
                'verbose_name': 'Organization contact',
                'verbose_name_plural': 'Organization contacts',
            },
            bases=('organization-network.person',),
        ),
        migrations.CreateModel(
            name='OrganizationUserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('title', models.CharField(max_length=1024, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file', models.FileField(max_length=1024, upload_to='images', verbose_name='Image')),
                ('credits', models.CharField(blank=True, max_length=256, null=True, verbose_name='credits')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='role',
            field=models.CharField(blank=True, choices=[('coordinator', 'coordinator'), ('producer', 'producer')], max_length=128, null=True, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='organizationuserimage',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_images', to='organization-network.Organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='organization-network.Organization', verbose_name='organization'),
        ),
    ]
