# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-13 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0090_auto_20170313_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='role',
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='role'),
        ),
    ]
