# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-30 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import organization.network.validators


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0090_auto_20170130_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personactivitytimesheet',
            name='percentage',
            field=models.IntegerField(help_text='Percentage has to be an integer between 0 and 100', validators=[organization.network.validators.is_percent], verbose_name='% of work time on the project'),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='default_percentage',
            field=models.IntegerField(blank=True, help_text='Percentage has to be an integer between 0 and 100', null=True, validators=[organization.network.validators.is_percent], verbose_name='default %'),
        ),
    ]
