# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-28 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0091_auto_20170130_1634'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectactivity',
            unique_together=set([('activity', 'project', 'default_percentage')]),
        ),
    ]
