# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-22 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0092_auto_20170314_1918'),
    ]

    operations = [
    ]
