# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-12 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0093_auto_20170301_1544'),
        ('organization-network', '0092_auto_20170314_1918'),
    ]

    operations = [
    ]
