# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-23 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0093_auto_20170322_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='position',
        ),
    ]
