# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-18 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0019_auto_20170415_0948'),
        ('organization-network', '0094_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='mezzanine_agenda.Event', verbose_name='event')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='organization-network.Organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Organization',
            },
        ),
    ]
