# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-31 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0095_auto_20170323_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('css_class', models.CharField(blank=True, help_text='Determine color on map.', max_length=64, null=True, verbose_name='class css')),
            ],
            options={
                'verbose_name': 'organization type',
                'ordering': ['name'],
            },
        ),
    ]
