# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-19 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0019_auto_20170415_0948'),
        ('organization-network', '0096_auto_20170418_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationeventlocation',
            name='event',
        ),
        migrations.AddField(
            model_name='organizationeventlocation',
            name='event_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='mezzanine_agenda.EventLocation', verbose_name='Event location'),
        ),
    ]
