# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-06 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0096_organizationrole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationrole',
            options={'ordering': ['name'], 'verbose_name': 'organization role'},
        ),
        migrations.RemoveField(
            model_name='organizationrole',
            name='css_class',
        ),
        migrations.AddField(
            model_name='organization',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization_network.OrganizationRole', verbose_name='organization role'),
        ),
    ]
