# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-12 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0101_organization_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationrole',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='name_en',
            field=models.CharField(max_length=512, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='name_fr',
            field=models.CharField(max_length=512, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='producerdata',
            name='producer_description',
            field=models.TextField(help_text='Description of the producer organization and the resources they bring for the proposal (100 to 150 words).', verbose_name='producer description'),
        ),
    ]
