# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-06-01 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('organization-network', '0104_auto_20170418_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='personlistblock',
            name='site',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
            preserve_default=False,
        ),
    ]
