# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-06-01 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('organization-network', '0105_personlistblock_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='personlistblockinline',
            name='site',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
            preserve_default=False,
        ),
    ]
