# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-26 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0096_auto_20171025_1123'),
        ('organization_network', '0107_organization_user'),
        ('organization_network', '0098_auto_20170427_1211'),
    ]

    operations = [
    ]
