# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-11-07 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-media', '0016_auto_20171107_1658'),
        ('organization-network', '0108_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias', to='organization-network.Department', verbose_name='department')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='organization-media.Media', verbose_name='media')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, verbose_name='URL'),
        ),
    ]
