# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-01-08 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0109_mediadepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerdata',
            name='experience_description',
            field=models.TextField(help_text='Do you have prior experience with working in organizations in a co-creation process? If so, please describe it. (40 to 60 words)', verbose_name='experience description'),
        ),
    ]
