# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-03-07 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0109_mediadepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.CharField(blank=True, default='', help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
