# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-05-02 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0111_auto_20180307_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='is main'),
        ),
        migrations.AddField(
            model_name='teamlink',
            name='title_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='teamlink',
            name='title_fr',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='title'),
        ),
    ]
