# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-05-14 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0112_auto_20180502_1742'),
        ('organization-network', '0110_auto_20180108_1203'),
    ]

    operations = [
    ]
