# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-31 10:54
from __future__ import unicode_literals

from django.db import migrations

def set_default_order(apps, schema_editor):
    Organization = apps.get_model('organization-network', 'Organization')
    organizations = Organization.objects.filter(_order__isnull=True)
    for organization in organizations :
        organization._order = 0
        organization.save()

class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0112_auto_20180502_1742'),
    ]

    operations = [
        migrations.RunPython(set_default_order),
    ]
