# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-06-01 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0112_auto_20180502_1742'),
        ('organization_network', '0110_auto_20180403_1406'),
    ]

    operations = [
    ]
