# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-04 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0115_auto_20181203_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='mappable_location',
            field=models.CharField(blank=True, help_text='This address will be used to calculate latitude and longitude. Leave blank and set Latitude and Longitude to specify the location yourself, or leave all three blank to auto-fill from the Location field.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='mappable_location',
            field=models.CharField(blank=True, help_text='This address will be used to calculate latitude and longitude. Leave blank and set Latitude and Longitude to specify the location yourself, or leave all three blank to auto-fill from the Location field.', max_length=512, null=True),
        ),
    ]
