# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-03 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0115_auto_20181203_2145'),
        ('organization-network', '0117_merge_20181116_1732'),
    ]

    operations = [
    ]
