# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-04 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0118_merge_20181203_2150'),
        ('organization-network', '0116_auto_20181204_1104'),
    ]

    operations = [
    ]
