# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-26 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0120_person_hal_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='hal_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='HAL id'),
        ),
    ]
