# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-15 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0120_merge_20181217_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='_meta_title',
            field=models.CharField(blank=True, help_text='Optional title to be used in the HTML title tag. If left blank, the main title field will be used.', max_length=500, null=True, verbose_name='Meta title'),
        ),
    ]
