# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-16 18:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization-core', '0006_citizenship'),
        ('organization-network', '0121_auto_20190515_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter', models.BooleanField(default=False, verbose_name='newsletter')),
                ('user_organization_notifications', models.BooleanField(default=False, verbose_name='Users and Organizations email notifications')),
                ('on_map', models.BooleanField(default=False, verbose_name='Appear on the Artistic Network Map')),
            ],
        ),
        migrations.CreateModel(
            name='PersonUserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('title', models.CharField(max_length=1024, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file', models.FileField(max_length=1024, upload_to='user/images/%Y/%m/%d/', verbose_name='Image')),
                ('credits', models.CharField(blank=True, max_length=256, null=True, verbose_name='credits')),
                ('type', models.CharField(choices=[('logo', 'logo'), ('logo_white', 'logo white'), ('logo_black', 'logo black'), ('logo_header', 'logo header'), ('logo_footer', 'logo footer'), ('slider', 'slider'), ('card', 'card'), ('page_slider', 'page - slider'), ('page_featured', 'page - featured'), ('header__responsive-logo-footer', 'responsive logo footer'), ('header__responsive-frame-video', 'responsive frame video')], max_length=64, null=True, verbose_name='type')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
        migrations.CreateModel(
            name='TestEmilie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('title', models.CharField(max_length=1024, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file', mezzanine.core.fields.FileField(max_length=1024, verbose_name='Image')),
                ('credits', models.CharField(blank=True, max_length=256, null=True, verbose_name='credits')),
                ('type', models.CharField(choices=[('logo', 'logo'), ('logo_white', 'logo white'), ('logo_black', 'logo black'), ('logo_header', 'logo header'), ('logo_footer', 'logo footer'), ('slider', 'slider'), ('card', 'card'), ('page_slider', 'page - slider'), ('page_featured', 'page - featured'), ('header__responsive-logo-footer', 'responsive logo footer'), ('header__responsive-frame-video', 'responsive frame video')], max_length=64, verbose_name='type')),
                ('image2', models.FileField(max_length=1024, upload_to='images', verbose_name='Image')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='address_2',
            field=models.TextField(blank=True, verbose_name='address 2'),
        ),
        migrations.AddField(
            model_name='organizationuserimage',
            name='type',
            field=models.CharField(choices=[('logo', 'logo'), ('logo_white', 'logo white'), ('logo_black', 'logo black'), ('logo_header', 'logo header'), ('logo_footer', 'logo footer'), ('slider', 'slider'), ('card', 'card'), ('page_slider', 'page - slider'), ('page_featured', 'page - featured'), ('header__responsive-logo-footer', 'responsive logo footer'), ('header__responsive-frame-video', 'responsive frame video')], max_length=64, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='person',
            name='address_2',
            field=models.TextField(blank=True, verbose_name='address 2'),
        ),
        migrations.AddField(
            model_name='person',
            name='citizenship',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization-core.Citizenship', verbose_name='citizenship'),
        ),
        migrations.AddField(
            model_name='person',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='telephone 2'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, verbose_name='address 1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True, verbose_name='address 1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='telephone',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='telephone 1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='personuserimage',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_images', to='organization-network.Person', verbose_name='person'),
        ),
        migrations.AddField(
            model_name='personoptions',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization-network.Person', verbose_name='person'),
        ),
    ]
