# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-27 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0121_organization_hal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagecustompersonlistblockinline',
            name='description',
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the filed defined by slug_field_name.', max_length=2000, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the filed defined by slug_field_name.', max_length=2000, null=True, verbose_name='URL'),
        ),
    ]
