# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-23 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0122_auto_20190516_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='person/background/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='person',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='person/profile/%Y/%m/%d'),
        ),
    ]
