# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-23 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0122_auto_20190117_1158'),
        ('organization-network', '0123_auto_20181227_1252'),
    ]

    operations = [
    ]
