# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-31 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0125_auto_20190130_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='in_sitemap',
        ),
        migrations.RemoveField(
            model_name='person',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='short_url',
        ),
        migrations.RemoveField(
            model_name='person',
            name='site',
        ),
        migrations.RemoveField(
            model_name='person',
            name='status',
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the filed defined by slug_field_name.', max_length=2000, null=True, verbose_name='URL'),
        ),
    ]
