# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-31 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0126_auto_20190131_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='site',
        ),
    ]
