# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-08 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0127_remove_organization_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectactivity',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activity', to='organization_projects.Project', verbose_name='project'),
        ),
    ]
