# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-21 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0128_auto_20190208_1540'),
        ('organization-network', '0113_teampage_user'),
    ]

    operations = [
    ]
