# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-04 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0130_dynamiccontentperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonRelatedTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1024, null=True, verbose_name='title')),
                ('title_fr', models.CharField(blank=True, max_length=1024, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, max_length=1024, null=True, verbose_name='title')),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_title', to='organization_network.Person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'related title',
            },
        ),
    ]
