# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-09 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0131_personrelatedtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personlistblockinline',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_list_block_inlines', to='organization-network.Person', verbose_name='Person'),
        ),
    ]
