# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-24 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0123_auto_20190523_1108'),
        ('organization-network', '0132_auto_20190409_1753'),
    ]

    operations = [
    ]
