# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-19 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0132_auto_20190409_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teampage',
            options={'ordering': ('_order',)},
        ),
        migrations.RemoveField(
            model_name='teampage',
            name='user',
        ),
    ]
