# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-09 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0134_auto_20190527_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='occupation',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='occupation'),
        ),
    ]
