# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-22 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0135_person_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personoptions',
            name='newsletter',
            field=models.BooleanField(default=False, help_text='You will receive a periodic Newsletter by email from the STARTS editorial team.', verbose_name='newsletter'),
        ),
        migrations.AlterField(
            model_name='personoptions',
            name='on_map',
            field=models.BooleanField(default=False, help_text='Your profile card will be displayed on the geographical community map if you add your own or professional address to your profile.', verbose_name='Appear on the Artistic Network Map'),
        ),
        migrations.AlterField(
            model_name='personoptions',
            name='user_organization_notifications',
            field=models.BooleanField(default=False, help_text='You will receive some email notifications when events concerning your profile and interactions occur.', verbose_name='Users and Organizations email notifications'),
        ),
    ]
