# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-10-06 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0136_auto_20190822_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityweeklyhourvolume',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='organizationblock',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='organizationimage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='organizationimage',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='organizationlinked',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='organizationlinkedblockinline',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='organizationlinkedinline',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='organizationuserimage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='pagecustompersonlistblockinline',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='personblock',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='personblock',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='personfile',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='personimage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='personimage',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='personlistblock',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='personlistblock',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='personuserimage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='title'),
        ),
    ]
