# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-04 21:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization-network', '0137_auto_20191006_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='following',
        ),
        migrations.AddField(
            model_name='person',
            name='following_organizations',
            field=models.ManyToManyField(blank=True, related_name='followers_organizations', to='organization-network.Organization', verbose_name='following_organizations'),
        ),
        migrations.AddField(
            model_name='person',
            name='following_users',
            field=models.ManyToManyField(blank=True, related_name='followers_users', to=settings.AUTH_USER_MODEL, verbose_name='following_users'),
        ),
    ]
