# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-09 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0138_auto_20191104_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonProfessionalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='professional_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='organization-network.PersonProfessionalCategory', verbose_name='professional category'),
        ),
    ]
