# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-15 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0140_auto_20200109_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSignupReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=512, verbose_name='reason')),
            ],
            options={
                'verbose_name': 'Signup reason',
                'verbose_name_plural': 'Signup reasons',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='signup_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_reason', to='organization-network.PersonSignupReason', verbose_name='How did you hear from us?'),
        ),
    ]
