# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-15 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0141_auto_20200115_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personoptions',
            name='newsletter',
            field=models.BooleanField(default=False, help_text='You will receive monthly newsletters by email from the STARTS editorial team!', verbose_name='newsletter'),
        ),
        migrations.AlterField(
            model_name='personoptions',
            name='on_map',
            field=models.BooleanField(default=False, help_text='Your profile will be accessible via our world map. For this, you need to inform your geo-localization (at least city and country).', verbose_name='Appear on the Artistic Network Map'),
        ),
        migrations.AlterField(
            model_name='personoptions',
            name='user_organization_notifications',
            field=models.BooleanField(default=False, help_text='Check the box not to miss any opportunity such as new STARTS calls for residencies, funding or exhibition. These are only sent to our members!', verbose_name='Users and Organizations email notifications'),
        ),
    ]
