# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-03 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0142_auto_20190703_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'organization'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='user',
        ),
    ]
