# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-15 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0142_auto_20200115_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='account_type',
            field=models.IntegerField(choices=[(0, 'Individual'), (1, 'Organization')], default=0, verbose_name='account type'),
            preserve_default=False,
        ),
    ]
