# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0143_auto_20190703_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='hal_researche_structure_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='HAL Researche Structure'),
        ),
        migrations.AddField(
            model_name='team',
            name='hal_researche_structure_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='HAL Researche Structure'),
        ),
    ]
