# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-06 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization_projects', '0092_auto_20200703_1644'),
        ('organization_network', '0144_auto_20200703_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamProjectOrdering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('project_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_projects.ProjectPage', verbose_name='Project')),
                ('team_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_network.TeamPage', verbose_name='Team')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
    ]
