# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-20 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0146_auto_20200720_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamprojectordering',
            name='project_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamprojectordering', to='organization-projects.ProjectPage', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='teamprojectordering',
            name='team_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamprojectordering', to='organization-network.TeamPage', verbose_name='Team'),
        ),
    ]
