# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-31 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('organization-network', '0148_teampage_order_projects_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprojectordering',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
            preserve_default=False,
        ),
    ]
