# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-10-22 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0144_person_is_referenced'),
        ('organization-network', '0149_teamprojectordering_site'),
    ]

    operations = [
    ]
