# Generated by Django 2.2.24 on 2021-08-23 15:53

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0150_merge_20201022_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystatus',
            name='display',
            field=models.BooleanField(blank=True, default=True, verbose_name='display on team page'),
        ),
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='organization_network.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='dynamiccontentperson',
            name='content_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='dynamicmultimediaorganization',
            name='content_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='dynamicmultimediaperson',
            name='content_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='mediadepartment',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='organization_media.Media', verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_host',
            field=models.BooleanField(blank=True, default=False, verbose_name='is host'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_main',
            field=models.BooleanField(blank=True, default=False, verbose_name='is main'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_on_map',
            field=models.BooleanField(blank=True, default=False, verbose_name='is on map'),
        ),
        migrations.AlterField(
            model_name='organizationimage',
            name='file',
            field=mezzanine.core.fields.FileField(max_length=1024, upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='organizationlink',
            name='link_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization_core.LinkType', verbose_name='link type'),
        ),
        migrations.AlterField(
            model_name='organizationlinkedblockinline',
            name='organization_linked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_linked_block_inline_list', to='organization_network.OrganizationLinked', verbose_name='organization list'),
        ),
        migrations.AlterField(
            model_name='organizationservice',
            name='image',
            field=mezzanine.core.fields.FileField(max_length=1024, upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='pagecustompersonlistblockinline',
            name='person_list_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_custom_person_list_block_inlines', to='organization_network.PersonListBlock', verbose_name='Person List Block'),
        ),
        migrations.AlterField(
            model_name='personactivity',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='organization_network.Person', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='personactivitytimesheet',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='organization_network.PersonActivity', verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='personactivitytimesheet',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='organization_projects.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='personactivityvacation',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization_network.PersonActivity', verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='personfile',
            name='file',
            field=mezzanine.core.fields.FileField(max_length=1024, upload_to='documents', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='personimage',
            name='file',
            field=mezzanine.core.fields.FileField(max_length=1024, upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='personlink',
            name='link_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization_core.LinkType', verbose_name='link type'),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activity', to='organization_network.PersonActivity', verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='teamlink',
            name='link_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization_core.LinkType', verbose_name='link type'),
        ),
        migrations.AlterField(
            model_name='teamprojectordering',
            name='project_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamprojectordering', to='organization_projects.ProjectPage', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='teamprojectordering',
            name='team_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamprojectordering', to='organization_network.TeamPage', verbose_name='Team'),
        ),
    ]
