# Generated by Django 3.2.18 on 2023-04-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0093_auto_20170322_1846'),
        ('organization_network', '0114_auto_20181002_1542'),
        ('organization_network', '0153_auto_20211202_1444'),
    ]

    operations = [
    ]
