# Generated by Django 3.2.18 on 2023-04-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0154_merge_20230424_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the filed defined by slug_field_name.', max_length=2000, null=True, verbose_name='URL'),
        ),
    ]
