# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageproductblock',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_blocks', to='pages.Page', verbose_name='page'),
        ),
    ]
