# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization_shop', '0003_productlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='productblock',
            name='content',
            field=mezzanine.core.fields.RichTextField(default='', verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productblock',
            name='content_en',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='productblock',
            name='content_fr',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='productblock',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='productblock',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
