# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-20 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20160907_1726'),
        ('organization_shop', '0005_auto_20160926_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrestashopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestashop_id', models.IntegerField(verbose_name='prestashop id')),
                ('prestashop_slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='slug')),
                ('prestashop_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='relative url')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prestashop_products', to='shop.Product', verbose_name='prestashop product')),
            ],
            options={
                'verbose_name': 'prestashop product',
                'verbose_name_plural': 'prestashop products',
            },
        ),
    ]
