# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-20 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_shop', '0006_productprestashopproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productprestashopproduct',
            old_name='prestashop_slug',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='productprestashopproduct',
            name='prestashop_id',
        ),
        migrations.RemoveField(
            model_name='productprestashopproduct',
            name='prestashop_url',
        ),
        migrations.AddField(
            model_name='productprestashopproduct',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='external id'),
        ),
        migrations.AddField(
            model_name='productprestashopproduct',
            name='url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='productprestashopproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prestashop_products', to='shop.Product', verbose_name='product'),
        ),
    ]
