# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-17 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20181227_1252'),
        ('organization-network', '0122_auto_20190117_1158'),
        ('organization-shop', '0009_auto_20161026_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='shop.Product', verbose_name='product')),
                ('teams', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organization-network.Team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
    ]
