# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-24 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-shop', '0010_auto_20180924_1057'),
        ('organization-shop', '0010_teamproduct'),
    ]

    operations = [
    ]
