# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-04 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_shop', '0011_auto_20191031_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productexternalshop',
            options={'verbose_name': 'external shop', 'verbose_name_plural': 'external shops'},
        ),
        migrations.AlterField(
            model_name='productexternalshop',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_external_shop', to='shop.Product', verbose_name='product'),
        ),
    ]
