# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-07 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20190703_1044'),
        ('sites', '0002_alter_domain_unique'),
        ('organization-shop', '0016_auto_20191105_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, verbose_name='URL')),
                ('product', models.ManyToManyField(blank=True, related_name='p_keywords', to='shop.Product', verbose_name='product')),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'Product Keyword',
                'verbose_name_plural': 'Product Keywords',
            },
        ),
    ]
