# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-11-06 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-shop', '0017_productkeyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productkeyword',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productkeyword',
            name='site',
        ),
        migrations.DeleteModel(
            name='ProductKeyword',
        ),
    ]
