# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization-core', '0010_auto_20160808_0118'),
        ('organization-project', '0002_auto_20160715_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('title', models.CharField(max_length=1024, verbose_name='title')),
                ('with_separator', models.BooleanField(default=False)),
                ('background_color', models.CharField(blank=True, choices=[('black', 'black'), ('yellow', 'yellow'), ('red', 'red')], max_length=32, verbose_name='background color')),
            ],
            options={
                'verbose_name': 'project block',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('file', mezzanine.core.fields.FileField(max_length=1024, verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='photo description')),
                ('credits', models.CharField(blank=True, max_length=256, null=True, verbose_name='photo credits')),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'project image',
            },
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('link_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization-core.LinkType', verbose_name='link type')),
            ],
            options={
                'verbose_name': 'project link',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'project'},
        ),
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.URLField(blank=True, max_length=512, verbose_name='website'),
        ),
        migrations.AddField(
            model_name='projectlink',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization-project.Project'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization-project.Project'),
        ),
        migrations.AddField(
            model_name='projectblock',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization-project.Project', verbose_name='project'),
        ),
    ]
