# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-team', '0016_auto_20160812_1521'),
        ('organization-project', '0004_auto_20160809_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='leader_team',
        ),
        migrations.RemoveField(
            model_name='project',
            name='partner_organizations',
        ),
        migrations.RemoveField(
            model_name='project',
            name='partner_persons',
        ),
        migrations.RemoveField(
            model_name='project',
            name='partner_teams',
        ),
        migrations.AddField(
            model_name='project',
            name='lead_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_projects', to='organization-team.Team', verbose_name='lead team'),
        ),
        migrations.AddField(
            model_name='project',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='organization-team.Organization', verbose_name='organizations'),
        ),
        migrations.AddField(
            model_name='project',
            name='persons',
            field=models.ManyToManyField(blank=True, to='organization-team.Person', verbose_name='persons'),
        ),
        migrations.AddField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='patner_projects', to='organization-team.Team', verbose_name='teams'),
        ),
    ]
