# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-project', '0006_auto_20160818_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_begin',
            field=models.DateField(blank=True, null=True, verbose_name='begin date'),
        ),
        migrations.AddField(
            model_name='project',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
    ]
