# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0010_auto_20160808_0118'),
        ('organization-team', '0013_auto_20160809_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='articles_related',
            field=models.ManyToManyField(blank=True, to='organization-magazine.Article', verbose_name='articles_related'),
        ),
    ]
