# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 05:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-project', '0007_auto_20160819_1920'),
        ('organization-team', '0016_auto_20160812_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFramework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
            ],
            options={
                'verbose_name': 'activity framework',
            },
        ),
        migrations.CreateModel(
            name='ActivityGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
            ],
            options={
                'verbose_name': 'activity grade',
            },
        ),
        migrations.CreateModel(
            name='ActivityStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
            ],
            options={
                'verbose_name': 'activity status',
            },
        ),
        migrations.CreateModel(
            name='BudgetCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
            ],
            options={
                'verbose_name': 'budget code',
            },
        ),
        migrations.CreateModel(
            name='RecordPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
            ],
            options={
                'verbose_name': 'record piece',
            },
        ),
        migrations.CreateModel(
            name='TrainingLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
            ],
            options={
                'verbose_name': 'training level',
            },
        ),
        migrations.CreateModel(
            name='TrainingSpectiality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
            ],
            options={
                'verbose_name': 'training speciality',
            },
        ),
        migrations.CreateModel(
            name='TrainingTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
            ],
            options={
                'verbose_name': 'training topic',
            },
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
            ],
            options={
                'verbose_name': 'training type',
            },
        ),
        migrations.RemoveField(
            model_name='personactivity',
            name='role',
        ),
        migrations.AddField(
            model_name='person',
            name='permanent',
            field=models.BooleanField(default=False, verbose_name='permanent'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='attachment_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachment_activity', to='organization-team.Organization', verbose_name='attachment organization'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='comments',
            field=models.TextField(blank=True, verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 23, 7, 44, 31, 896290), verbose_name='add date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personactivity',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 23, 7, 44, 41, 729673), verbose_name='modification date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personactivity',
            name='date_modified_manual',
            field=models.DateTimeField(blank=True, null=True, verbose_name='manual modification date'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_activity', to='organization-team.Organization', verbose_name='employer'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='function',
            field=models.CharField(blank=True, max_length=1024, verbose_name='fonction'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='hdr',
            field=models.BooleanField(default=False, verbose_name='HDR'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='phd_defense_date',
            field=models.DateField(blank=True, null=True, verbose_name='PhD defense date'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='phd_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phd_director_activity', to='organization-team.Person', verbose_name='PhD director'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='phd_doctoral_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization-team.Organization', verbose_name='doctoral school'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='phd_officer_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phd_officer_1_activity', to='organization-team.Person', verbose_name='PhD officer 1'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='phd_officer_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phd_officer_2_activity', to='organization-team.Person', verbose_name='PhD officer 2'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='phd_postdoctoralsituation',
            field=models.CharField(blank=True, max_length=256, verbose_name='post-doctoral situation'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='phd_title',
            field=models.TextField(blank=True, verbose_name='PhD title'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization-project.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='rd_program',
            field=models.TextField(blank=True, verbose_name='R&D program'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='rd_quota',
            field=models.IntegerField(blank=True, null=True, verbose_name='R&D quota'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='second_employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_employer_activity', to='organization-team.Organization', verbose_name='second employer'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='second_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_team_activity', to='organization-team.Team', verbose_name='second team'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='training_title',
            field=models.TextField(blank=True, verbose_name='Training title'),
        ),
        migrations.AlterField(
            model_name='personactivity',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_activity', to='organization-team.Team', verbose_name='team'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='budget_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization-team.BudgetCode'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization-team.ActivityFramework', verbose_name='framework'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization-team.ActivityGrade', verbose_name='grade'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='record_piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization-team.RecordPiece'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization-team.ActivityStatus', verbose_name='status'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='training_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization-team.TrainingLevel', verbose_name='training level'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='training_speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization-team.TrainingSpectiality', verbose_name='training speciality'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='training_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization-team.TrainingTopic', verbose_name='training topic'),
        ),
        migrations.AddField(
            model_name='personactivity',
            name='training_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization-team.TrainingType', verbose_name='training type'),
        ),
    ]
