# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization-media', '__first__'),
        ('organization-core', '0001_initial'),
        ('mezzanine_agenda', '__first__'),
        ('organization-magazine', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('articles', models.ManyToManyField(blank=True, related_name='featured', to='organization-magazine.Article', verbose_name='articles')),
                ('briefs', models.ManyToManyField(blank=True, related_name='featured', to='organization-magazine.Brief', verbose_name='briefs')),
                ('events', models.ManyToManyField(blank=True, related_name='featured', to='mezzanine_agenda.Event', verbose_name='events')),
                ('pages', models.ManyToManyField(blank=True, related_name='featured', to='organization-core.BasicPage', verbose_name='pages')),
                ('playlists', models.ManyToManyField(blank=True, related_name='featured', to='organization-media.Playlist', verbose_name='playlists')),
                ('videos', models.ManyToManyField(blank=True, related_name='featured', to='organization-media.Video', verbose_name='videos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
