# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization magazine', '0006_auto_20160711_1200'),
        ('featured', '0002_auto_20160707_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='briefs',
            field=models.ManyToManyField(blank=True, related_name='featured', to='organization magazine.Brief', verbose_name='briefs'),
        ),
    ]
