# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-01 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_content_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content_model',
        ),
    ]
