# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0002_auto_20160823_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='site',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='title',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='website',
        ),
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(default='', max_length=512, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='web_site',
            field=models.URLField(blank=True, max_length=512, verbose_name='web site'),
        ),
    ]
