# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-network', '0010_personautocomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='personautocomplete',
            name='persons',
            field=models.ManyToManyField(to='organization-network.Person'),
        ),
    ]
