# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization magazine', '0002_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-publish_date',), 'verbose_name': 'article', 'verbose_name_plural': 'article'},
        ),
    ]
