# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0003_auto_20160728_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_article',
            field=models.ManyToManyField(blank=True, related_name='_article_related_article_+', to='organization-magazine.Article', verbose_name='Related posts'),
        ),
    ]
