# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization magazine', '0003_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='local_content',
            field=models.CharField(blank=True, max_length=1000, verbose_name='local content'),
        ),
        migrations.AddField(
            model_name='brief',
            name='local_content_en',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='local content'),
        ),
        migrations.AddField(
            model_name='brief',
            name='local_content_fr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='local content'),
        ),
    ]
