# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0004_article_related_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='related_article',
        ),
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='_article_related_articles_+', to='organization-magazine.Article', verbose_name='Related posts'),
        ),
    ]
