# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization magazine', '0003_auto_20160708_1236'),
        ('organization magazine', '0004_auto_20160707_1544'),
    ]

    operations = [
    ]
