# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0005_auto_20160728_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='_article_related_articles_+', to='organization-magazine.Article', verbose_name='Related articles'),
        ),
    ]
