# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization magazine', '0005_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'article'},
        ),
    ]
