# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization magazine', '0006_auto_20160711_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='local_content',
            field=models.URLField(max_length=1000, verbose_name='local content'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='local_content_en',
            field=models.URLField(max_length=1000, null=True, verbose_name='local content'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='local_content_fr',
            field=models.URLField(max_length=1000, null=True, verbose_name='local content'),
        ),
    ]
