# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 12:51
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0007_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content',
            field=mezzanine.core.fields.RichTextField(default='', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
