# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0008_topic_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='parent_topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type', to='organization-magazine.Topic', verbose_name='topic'),
            preserve_default=False,
        ),
    ]
