# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0009_auto_20160825_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='organization-network.Department', verbose_name='department'),
        ),
    ]
