# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0012_auto_20160812_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='brief',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content page'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='object_id',
            field=models.PositiveIntegerField(null=True, verbose_name='related object'),
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
