# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization-magazine', '0014_auto_20160818_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='content_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content page'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='object_id',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='related object'),
        ),
    ]
