# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0012_auto_20160405_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='poster',
            field=models.URLField(blank=True, max_length=1024, verbose_name='poster'),
        ),
        migrations.AddField(
            model_name='video',
            name='poster',
            field=models.URLField(blank=True, max_length=1024, verbose_name='poster'),
        ),
    ]
