# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0015_auto_20160407_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featured',
            old_name='blogpost',
            new_name='blogposts',
        ),
    ]
