# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0016_auto_20160407_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featured',
            old_name='page',
            new_name='pages',
        ),
    ]
