# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0017_auto_20160407_2256'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pagecategory',
            table='festival_page_category',
        ),
    ]
