# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0018_auto_20160407_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='blogposts',
            field=models.ManyToManyField(blank=True, related_name='featured', to='blog.BlogPost', verbose_name='blog posts'),
        ),
        migrations.AlterField(
            model_name='featured',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='featured', to='pages.Page', verbose_name='pages'),
        ),
    ]
