# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-17 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0021_delete_pagecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='audios', to='festival.Artist', verbose_name='artists'),
        ),
        migrations.AddField(
            model_name='video',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='videos', to='festival.Artist', verbose_name='artists'),
        ),
    ]
