# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_auto_20141227_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='title_fr',
            field=models.CharField(max_length=500, null=True, verbose_name='Title'),
        ),
    ]
