# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-12 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20170223_1257'),
        ('pages', '0006_auto_20170223_2352'),
    ]

    operations = [
    ]
