# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_network', '0005_auto_20160905_1853'),
        ('mezzanine_agenda', '0005_auto_20160907_1541'),
        ('organization_agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='organization_network.Department', verbose_name='department')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='mezzanine_agenda.Event', verbose_name='event')),
            ],
            options={
                'verbose_name_plural': 'departments',
                'verbose_name': 'department',
            },
        ),
    ]
