# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_agenda', '0006_auto_20160929_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventaudio',
            name='audio_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization_media.Audio'),
        ),
        migrations.AlterField(
            model_name='eventvideo',
            name='video_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization_media.Video'),
        ),
    ]
