# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-20 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_agenda', '0011_auto_20161018_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtraining',
            name='language',
            field=models.CharField(blank=True, choices=[('fr', 'French'), ('en', 'English')], max_length=64, null=True, verbose_name='language'),
        ),
    ]
