# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_agenda', '0012_auto_20161020_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlink',
            name='title',
            field=models.CharField(default='', max_length=1024, verbose_name='title'),
            preserve_default=False,
        ),
    ]
