# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-07 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0015_auto_20161021_1937'),
        ('organization_agenda', '0018_auto_20161104_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPriceDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('event_price', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_price_description', to='mezzanine_agenda.EventPrice', verbose_name='event_price_description')),
            ],
            options={
                'verbose_name': 'Additionnal description',
            },
        ),
    ]
