# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-06 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-agenda', '0022_auto_20170105_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventperiod',
            options={'ordering': ['date_from'], 'verbose_name': 'period', 'verbose_name_plural': 'periods'},
        ),
    ]
