# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-21 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0016_auto_20161216_1558'),
        ('organization-agenda', '0023_auto_20170214_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='rank')),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_rank', to='mezzanine_agenda.Event', verbose_name='event')),
            ],
            options={
                'verbose_name_plural': 'ranks',
                'verbose_name': 'rank',
            },
        ),
    ]
