# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-22 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-agenda', '0024_eventrank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrank',
            name='event',
        ),
        migrations.DeleteModel(
            name='EventRank',
        ),
    ]
