# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-13 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-agenda', '0025_auto_20170222_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtraining',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French')], max_length=64, null=True, verbose_name='language'),
        ),
    ]
