# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-26 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_agenda', '0028_auto_20170427_1211'),
        ('organization_agenda', '0023_auto_20170406_1514'),
    ]

    operations = [
    ]
