# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-16 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-agenda', '0032_auto_20181108_1636'),
        ('organization-agenda', '0033_auto_20181105_2349'),
    ]

    operations = [
    ]
