# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-08 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization-agenda', '0034_auto_20190130_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventblock',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='eventblock',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='eventblock',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='credits_en',
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='eventlink',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='eventpricedescription',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='eventpublictype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='eventrelatedtitle',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='eventtraininglevel',
            name='name_en',
        ),
        migrations.AlterField(
            model_name='eventtraining',
            name='language',
            field=models.CharField(blank=True, choices=[('fr', 'French')], max_length=64, null=True, verbose_name='language'),
        ),
    ]
