# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-24 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization-agenda', '0034_auto_20190130_1553'),
        ('organization-agenda', '0035_auto_20181212_1211'),
    ]

    operations = [
    ]
