# Generated by Django 3.2.18 on 2023-04-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_agenda', '0037_merge_0031_auto_20181002_1542_0036_auto_20210823_1753'),
    ]

    operations = [
    ]
