name: Lint
on: [push, pull_request]
jobs:
  flake8-lint:
    runs-on: python:3.7.5-buster
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.7.5"
      - name: flake8 Lint
        uses: py-actions/flake8@v1
